import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Generate a massive list of fish species covering saltwater, freshwater, tropical, deep-sea, etc.
function generateFishSpecies() {
  const species: any[] = [];

  const saltwaterFish = [
    { name_en: "Atlantic Sailfish", latin_name: "Istiophorus albicans", category: "saltwater", habitat: "Atlantic Ocean, pelagic", techniques: ["Trolling","Fly fishing"], baits: ["Ballyhoo","Strip baits","Poppers"], description: "Fast predator with a tall dorsal sail." },
    { name_en: "Pacific Sailfish", latin_name: "Istiophorus platypterus", category: "saltwater", habitat: "Indo-Pacific Ocean", techniques: ["Trolling","Live bait"], baits: ["Live mackerel","Rigged ballyhoo"], description: "Fastest fish in the ocean, reaching 68 mph." },
    { name_en: "Blue Marlin", latin_name: "Makaira nigricans", category: "saltwater", habitat: "Tropical and temperate Atlantic", techniques: ["Trolling"], baits: ["Large lures","Rigged baits","Tuna belly"], description: "Iconic big game fish reaching over 1000 lbs." },
    { name_en: "White Marlin", latin_name: "Kajikia albida", category: "saltwater", habitat: "Western Atlantic", techniques: ["Trolling","Drifting"], baits: ["Ballyhoo","Squid strips"], description: "Smaller marlin species prized for sport." },
    { name_en: "Striped Marlin", latin_name: "Kajikia audax", category: "saltwater", habitat: "Indo-Pacific", techniques: ["Trolling","Live bait"], baits: ["Live mackerel","Skipjack"], description: "Acrobatic marlin known for tail-walking." },
    { name_en: "Black Marlin", latin_name: "Istiompax indica", category: "saltwater", habitat: "Indo-Pacific tropical waters", techniques: ["Trolling","Live bait"], baits: ["Live tuna","Large lures"], description: "One of the largest bony fish, up to 1500 lbs." },
    { name_en: "Swordfish", latin_name: "Xiphias gladius", category: "saltwater", habitat: "Deep oceanic waters worldwide", techniques: ["Deep dropping","Night fishing"], baits: ["Squid","Mackerel","Light sticks"], description: "Deep-water predator with a flattened bill." },
    { name_en: "Yellowfin Tuna", latin_name: "Thunnus albacares", category: "saltwater", habitat: "Tropical and subtropical oceans", techniques: ["Trolling","Chunking","Jigging"], baits: ["Cedar plugs","Poppers","Live bait"], description: "Powerful pelagic fish reaching 400+ lbs." },
    { name_en: "Bluefin Tuna", latin_name: "Thunnus thynnus", category: "saltwater", habitat: "Atlantic Ocean", techniques: ["Trolling","Chunking"], baits: ["Live herring","Mackerel","Giant poppers"], description: "Most valuable commercial fish, can exceed 1000 lbs." },
    { name_en: "Bigeye Tuna", latin_name: "Thunnus obesus", category: "saltwater", habitat: "Deep tropical oceans", techniques: ["Deep dropping","Trolling"], baits: ["Squid","Deep jigs"], description: "Deep-dwelling tuna with large eyes for low light." },
    { name_en: "Skipjack Tuna", latin_name: "Katsuwonus pelamis", category: "saltwater", habitat: "Tropical oceans worldwide", techniques: ["Trolling","Casting"], baits: ["Small lures","Feathers"], description: "Most abundant tuna species. Fast schooling fish." },
    { name_en: "Albacore Tuna", latin_name: "Thunnus alalunga", category: "saltwater", habitat: "Temperate oceans", techniques: ["Trolling","Jigging"], baits: ["Cedar plugs","Feather jigs"], description: "Long-finned tuna prized for canning and sport." },
    { name_en: "Blackfin Tuna", latin_name: "Thunnus atlanticus", category: "saltwater", habitat: "Western Atlantic", techniques: ["Trolling","Chunking"], baits: ["Small lures","Live pilchards"], description: "Smallest tuna species in Atlantic. Great fighter." },
    { name_en: "Wahoo", latin_name: "Acanthocybium solandri", category: "saltwater", habitat: "Tropical oceans worldwide", techniques: ["High-speed trolling"], baits: ["Wahoo lures","Rigged ballyhoo"], description: "One of fastest fish, reaching 60 mph. Excellent table fare." },
    { name_en: "King Mackerel", latin_name: "Scomberomorus cavalla", category: "saltwater", habitat: "Western Atlantic, Gulf of Mexico", techniques: ["Trolling","Live bait","Drifting"], baits: ["Live menhaden","Cigar minnows","Spoons"], description: "Fast predator popular in Gulf and Atlantic fisheries." },
    { name_en: "Spanish Mackerel", latin_name: "Scomberomorus maculatus", category: "saltwater", habitat: "Western Atlantic coast", techniques: ["Casting","Trolling"], baits: ["Gotcha plugs","Spoons","Shrimp"], description: "Fast coastal pelagic with spotted sides." },
    { name_en: "Cero Mackerel", latin_name: "Scomberomorus regalis", category: "saltwater", habitat: "Western Atlantic, Caribbean", techniques: ["Trolling","Casting"], baits: ["Small lures","Live bait"], description: "Tropical mackerel found around reefs." },
    { name_en: "Mahi-Mahi", latin_name: "Coryphaena hippurus", category: "saltwater", habitat: "Tropical and subtropical oceans", techniques: ["Trolling","Casting"], baits: ["Ballyhoo","Feather lures","Live bait"], description: "Brilliant colors and acrobatic jumps. Excellent eating." },
    { name_en: "Pompano Dolphinfish", latin_name: "Coryphaena equiselis", category: "saltwater", habitat: "Tropical oceans", techniques: ["Trolling"], baits: ["Small lures","Feathers"], description: "Smaller cousin of mahi-mahi." },
    { name_en: "Greater Amberjack", latin_name: "Seriola dumerili", category: "saltwater", habitat: "Tropical and temperate reefs", techniques: ["Jigging","Live bait","Bottom fishing"], baits: ["Live blue runners","Vertical jigs","Poppers"], description: "Powerful reef fish known as 'reef donkey'." },
    { name_en: "Lesser Amberjack", latin_name: "Seriola fasciata", category: "saltwater", habitat: "Deep reefs, Western Atlantic", techniques: ["Deep jigging"], baits: ["Vertical jigs","Cut bait"], description: "Smaller amberjack found in deeper waters." },
    { name_en: "Almaco Jack", latin_name: "Seriola rivoliana", category: "saltwater", habitat: "Deep reefs worldwide", techniques: ["Jigging","Bottom fishing"], baits: ["Live bait","Vertical jigs"], description: "Deep-dwelling jack with dark coloring." },
    { name_en: "California Yellowtail", latin_name: "Seriola dorsalis", category: "saltwater", habitat: "Eastern Pacific", techniques: ["Trolling","Casting","Jigging"], baits: ["Live sardines","Iron jigs","Swimbaits"], description: "Premier sport fish of Southern California." },
    { name_en: "Banded Rudderfish", latin_name: "Seriola zonata", category: "saltwater", habitat: "Western Atlantic", techniques: ["Light tackle","Jigging"], baits: ["Small jigs","Live bait"], description: "Juvenile rudderfish follow floating objects." },
    { name_en: "Florida Pompano", latin_name: "Trachinotus carolinus", category: "saltwater", habitat: "Surf zones, Atlantic and Gulf", techniques: ["Surf fishing","Casting"], baits: ["Sand fleas","Shrimp","Pompano jigs"], description: "Prized surf fish with excellent table quality." },
    { name_en: "Permit", latin_name: "Trachinotus falcatus", category: "saltwater", habitat: "Tropical flats and reefs", techniques: ["Fly fishing","Sight casting"], baits: ["Crab flies","Live crabs","Shrimp"], description: "Ultimate flats fishing challenge. Extremely wary." },
    { name_en: "African Pompano", latin_name: "Alectis ciliaris", category: "saltwater", habitat: "Tropical reefs worldwide", techniques: ["Jigging","Bottom fishing"], baits: ["Live bait","Jigs"], description: "Diamond-shaped jack with trailing filaments." },
    { name_en: "Crevalle Jack", latin_name: "Caranx hippos", category: "saltwater", habitat: "Tropical and subtropical Atlantic", techniques: ["Casting","Fly fishing","Trolling"], baits: ["Poppers","Live mullet","Spoons"], description: "Powerful school fish that blitzes baitfish on surface." },
    { name_en: "Horse-Eye Jack", latin_name: "Caranx latus", category: "saltwater", habitat: "Tropical Atlantic reefs", techniques: ["Casting","Trolling"], baits: ["Poppers","Jigs","Live bait"], description: "Large-eyed jack of reef edges." },
    { name_en: "Bar Jack", latin_name: "Caranx ruber", category: "saltwater", habitat: "Caribbean reefs", techniques: ["Light tackle"], baits: ["Small jigs","Live bait"], description: "Colorful reef jack with a blue-black stripe." },
    { name_en: "Blue Runner", latin_name: "Caranx crysos", category: "saltwater", habitat: "Western Atlantic", techniques: ["Casting","Jigging"], baits: ["Small jigs","Sabiki rigs"], description: "Common jack used as live bait for larger species." },
    { name_en: "Giant Trevally", latin_name: "Caranx ignobilis", category: "saltwater", habitat: "Indo-Pacific", techniques: ["Popping","Jigging","Fly fishing"], baits: ["Large poppers","Stickbaits","GT flies"], description: "Apex reef predator. Most powerful jack species." },
    { name_en: "Bluefin Trevally", latin_name: "Caranx melampygus", category: "saltwater", habitat: "Indo-Pacific reefs", techniques: ["Casting","Jigging"], baits: ["Poppers","Jigs","Flies"], description: "Electric blue fins and aggressive feeding." },
    { name_en: "Golden Trevally", latin_name: "Gnathanodon speciosus", category: "saltwater", habitat: "Indo-Pacific", techniques: ["Fly fishing","Casting"], baits: ["Flies","Small lures"], description: "Golden-barred juvenile follows sharks and rays." },
    { name_en: "Roosterfish", latin_name: "Nematistius pectoralis", category: "saltwater", habitat: "Eastern Pacific, surf zones", techniques: ["Surf casting","Live bait"], baits: ["Live mullet","Poppers","Swimbaits"], description: "Iconic Pacific sport fish with rooster-comb dorsal." },
    { name_en: "Bonefish", latin_name: "Albula vulpes", category: "saltwater", habitat: "Tropical flats worldwide", techniques: ["Fly fishing","Sight casting"], baits: ["Shrimp flies","Gotcha","Live shrimp"], description: "Ghost of the flats. Premier fly fishing target." },
    { name_en: "Tarpon", latin_name: "Megalops atlanticus", category: "saltwater", habitat: "Tropical Atlantic, estuaries", techniques: ["Fly fishing","Live bait","Casting"], baits: ["Live crabs","Mullet","Tarpon flies"], description: "Silver King. Spectacular jumper reaching 200+ lbs." },
    { name_en: "Indo-Pacific Tarpon", latin_name: "Megalops cyprinoides", category: "saltwater", habitat: "Indo-Pacific estuaries", techniques: ["Fly fishing","Light tackle"], baits: ["Small flies","Live shrimp"], description: "Smaller Indo-Pacific cousin of Atlantic tarpon." },
    { name_en: "Snook", latin_name: "Centropomus undecimalis", category: "saltwater", habitat: "Tropical Atlantic, mangroves", techniques: ["Casting","Fly fishing","Live bait"], baits: ["Live pilchards","Swimbaits","Snook flies"], description: "Top inshore predator of Florida and Caribbean." },
    { name_en: "Red Snapper", latin_name: "Lutjanus campechanus", category: "saltwater", habitat: "Gulf of Mexico reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Cut bait","Squid","Live cigar minnows"], description: "Premier Gulf reef fish. Strictly managed." },
    { name_en: "Yellowtail Snapper", latin_name: "Ocyurus chrysurus", category: "saltwater", habitat: "Caribbean and Florida reefs", techniques: ["Chumming","Light tackle"], baits: ["Cut bait","Shrimp","Small jigs"], description: "Colorful reef snapper with a yellow tail stripe." },
    { name_en: "Mangrove Snapper", latin_name: "Lutjanus griseus", category: "saltwater", habitat: "Mangroves, docks, reefs", techniques: ["Bottom fishing","Casting"], baits: ["Live shrimp","Cut bait","Jigs"], description: "Wary nearshore snapper. Excellent eating." },
    { name_en: "Mutton Snapper", latin_name: "Lutjanus analis", category: "saltwater", habitat: "Florida and Caribbean reefs", techniques: ["Bottom fishing","Live bait"], baits: ["Live ballyhoo","Shrimp","Crabs"], description: "Large snapper found near reef ledges." },
    { name_en: "Lane Snapper", latin_name: "Lutjanus synagris", category: "saltwater", habitat: "Western Atlantic reefs", techniques: ["Bottom fishing","Light tackle"], baits: ["Shrimp","Cut bait","Small jigs"], description: "Pink snapper with yellow stripes. Great eating." },
    { name_en: "Cubera Snapper", latin_name: "Lutjanus cyanopterus", category: "saltwater", habitat: "Tropical Atlantic, deep reefs", techniques: ["Heavy bottom fishing"], baits: ["Live lobster","Live blue crabs"], description: "Largest Atlantic snapper, over 100 lbs." },
    { name_en: "Dog Snapper", latin_name: "Lutjanus jocu", category: "saltwater", habitat: "Caribbean and Florida reefs", techniques: ["Bottom fishing"], baits: ["Cut bait","Live bait"], description: "Large snapper with prominent canine teeth." },
    { name_en: "Schoolmaster Snapper", latin_name: "Lutjanus apodus", category: "saltwater", habitat: "Caribbean reefs and mangroves", techniques: ["Light tackle","Casting"], baits: ["Shrimp","Cut bait"], description: "Yellowish snapper found in schools near structure." },
    { name_en: "Silk Snapper", latin_name: "Lutjanus vivanus", category: "saltwater", habitat: "Deep reefs, Western Atlantic", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "Deep-water snapper with a pinkish body." },
    { name_en: "Vermilion Snapper", latin_name: "Rhomboplites aurorubens", category: "saltwater", habitat: "Atlantic reefs, 60-300 ft", techniques: ["Bottom fishing"], baits: ["Squid strips","Cut bait","Small jigs"], description: "Small but abundant reef snapper, great flavor." },
    { name_en: "Red Drum", latin_name: "Sciaenops ocellatus", category: "saltwater", habitat: "Atlantic and Gulf coastal waters", techniques: ["Sight casting","Fly fishing","Bottom fishing"], baits: ["Live shrimp","Cut mullet","Gold spoons"], description: "Iconic inshore species. AKA Redfish." },
    { name_en: "Black Drum", latin_name: "Pogonias cromis", category: "saltwater", habitat: "Atlantic and Gulf estuaries", techniques: ["Bottom fishing","Surf fishing"], baits: ["Crabs","Shrimp","Clams"], description: "Large drum species exceeding 90 lbs." },
    { name_en: "Spotted Seatrout", latin_name: "Cynoscion nebulosus", category: "saltwater", habitat: "Atlantic and Gulf inshore", techniques: ["Casting","Fly fishing","Drifting"], baits: ["Live shrimp","Soft plastics","Topwater"], description: "Premier inshore game fish of the Southeast." },
    { name_en: "Weakfish", latin_name: "Cynoscion regalis", category: "saltwater", habitat: "Atlantic coast estuaries", techniques: ["Casting","Trolling"], baits: ["Bucktail jigs","Live bait","Soft plastics"], description: "Delicate-mouthed relative of seatrout." },
    { name_en: "Red Grouper", latin_name: "Epinephelus morio", category: "saltwater", habitat: "Gulf of Mexico reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Live pinfish","Squid","Cut bait"], description: "Common Gulf grouper. Excellent table fare." },
    { name_en: "Black Grouper", latin_name: "Mycteroperca bonaci", category: "saltwater", habitat: "Tropical Atlantic reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Live bait","Large jigs"], description: "Large reef grouper reaching 100+ lbs." },
    { name_en: "Gag Grouper", latin_name: "Mycteroperca microlepis", category: "saltwater", habitat: "Atlantic and Gulf reefs", techniques: ["Bottom fishing","Trolling"], baits: ["Live pinfish","Large jigs","Swimbaits"], description: "Popular grouper target in Southeast US." },
    { name_en: "Goliath Grouper", latin_name: "Epinephelus itajara", category: "saltwater", habitat: "Tropical Atlantic, wrecks and bridges", techniques: ["Heavy tackle","Live bait"], baits: ["Live jack","Live mullet"], description: "Massive grouper exceeding 800 lbs. Protected in most areas." },
    { name_en: "Nassau Grouper", latin_name: "Epinephelus striatus", category: "saltwater", habitat: "Caribbean coral reefs", techniques: ["Bottom fishing"], baits: ["Live bait","Cut bait"], description: "Endangered Caribbean grouper with color-changing ability." },
    { name_en: "Yellowfin Grouper", latin_name: "Mycteroperca venenosa", category: "saltwater", habitat: "Caribbean and Bahamas reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Live bait","Jigs"], description: "Colorful deep reef grouper." },
    { name_en: "Scamp Grouper", latin_name: "Mycteroperca phenax", category: "saltwater", habitat: "Deep reefs, Gulf and Atlantic", techniques: ["Deep jigging","Bottom fishing"], baits: ["Live bait","Squid","Jigs"], description: "Highly prized deep-water grouper." },
    { name_en: "Warsaw Grouper", latin_name: "Hyporthodus nigritus", category: "saltwater", habitat: "Deep reefs 300-600 ft", techniques: ["Deep dropping"], baits: ["Large cut bait","Squid"], description: "Deep-water giant grouper." },
    { name_en: "Yellowedge Grouper", latin_name: "Hyporthodus flavolimbatus", category: "saltwater", habitat: "Deep reefs, Gulf of Mexico", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "Deep-water grouper with yellow fin margins." },
    { name_en: "Snowy Grouper", latin_name: "Hyporthodus niveatus", category: "saltwater", habitat: "Deep reefs 300-700 ft", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "White-spotted deep-water grouper." },
    { name_en: "Speckled Hind", latin_name: "Epinephelus drummondhayi", category: "saltwater", habitat: "Deep Atlantic reefs", techniques: ["Deep dropping"], baits: ["Cut bait","Squid"], description: "Rare deep-water grouper. Heavily protected." },
    { name_en: "Tiger Grouper", latin_name: "Mycteroperca tigris", category: "saltwater", habitat: "Caribbean coral reefs", techniques: ["Bottom fishing"], baits: ["Live bait","Cut bait"], description: "Distinctly barred Caribbean grouper." },
    { name_en: "Coney", latin_name: "Cephalopholis fulva", category: "saltwater", habitat: "Caribbean reefs", techniques: ["Light tackle"], baits: ["Small jigs","Cut bait"], description: "Small colorful reef grouper found in Caribbean." },
    { name_en: "Rock Hind", latin_name: "Epinephelus adscensionis", category: "saltwater", habitat: "Atlantic reefs", techniques: ["Bottom fishing"], baits: ["Shrimp","Cut bait"], description: "Spotted reef grouper of the Atlantic." },
    { name_en: "Tripletail", latin_name: "Lobotes surinamensis", category: "saltwater", habitat: "Tropical/subtropical, near floating objects", techniques: ["Sight casting","Fly fishing"], baits: ["Live shrimp","Soft plastics","Crab flies"], description: "Floats on its side near buoys. Incredible table fare." },
    { name_en: "Cobia", latin_name: "Rachycentron canadum", category: "saltwater", habitat: "Tropical/subtropical coastal", techniques: ["Sight casting","Live bait","Jigging"], baits: ["Live eels","Jigs","Live crabs"], description: "Powerful coastal migrator following rays and sharks." },
    { name_en: "Sheepshead", latin_name: "Archosargus probatocephalus", category: "saltwater", habitat: "Atlantic and Gulf pilings/bridges", techniques: ["Bottom fishing","Structure fishing"], baits: ["Fiddler crabs","Shrimp","Barnacles"], description: "Black-banded fish with human-like teeth. Steals bait." },
    { name_en: "Tautog (Blackfish)", latin_name: "Tautoga onitis", category: "saltwater", habitat: "Northeast Atlantic reefs/wrecks", techniques: ["Bottom fishing"], baits: ["Green crabs","Asian shore crabs","Clams"], description: "Northeast wreck dweller. Excellent winter fishing." },
    { name_en: "Cunner", latin_name: "Tautogolabrus adspersus", category: "saltwater", habitat: "Northeast Atlantic, rocky areas", techniques: ["Light tackle"], baits: ["Worms","Clams","Small jigs"], description: "Small wrasse-like fish of the Northeast coast." },
    { name_en: "Scup (Porgy)", latin_name: "Stenotomus chrysops", category: "saltwater", habitat: "Northeast Atlantic coast", techniques: ["Bottom fishing","Light tackle"], baits: ["Squid strips","Clam","Worms"], description: "Common Northeast bottom fish. Fun on light tackle." },
    { name_en: "Red Porgy", latin_name: "Pagrus pagrus", category: "saltwater", habitat: "Atlantic reefs, 60-300 ft", techniques: ["Bottom fishing"], baits: ["Squid","Cut bait","Shrimp"], description: "Pink-colored reef fish. Good eating." },
    { name_en: "Jolthead Porgy", latin_name: "Calamus bajonado", category: "saltwater", habitat: "Tropical Atlantic reefs", techniques: ["Bottom fishing","Light tackle"], baits: ["Shrimp","Sea urchin","Crabs"], description: "Large porgy found near reefs." },
    { name_en: "Longspine Porgy", latin_name: "Stenotomus caprinus", category: "saltwater", habitat: "Gulf of Mexico", techniques: ["Bottom fishing"], baits: ["Shrimp","Squid"], description: "Gulf cousin of the Atlantic scup." },
    { name_en: "Ocean Triggerfish", latin_name: "Canthidermis sufflamen", category: "saltwater", habitat: "Pelagic, tropical oceans", techniques: ["Fly fishing","Light tackle"], baits: ["Small flies","Cut bait"], description: "Pelagic triggerfish found under floating debris." },
    { name_en: "Gray Triggerfish", latin_name: "Balistes capriscus", category: "saltwater", habitat: "Atlantic and Gulf reefs", techniques: ["Bottom fishing"], baits: ["Squid","Shrimp","Cut bait"], description: "Reef dweller with tough skin and strong teeth." },
    { name_en: "Queen Triggerfish", latin_name: "Balistes vetula", category: "saltwater", habitat: "Caribbean coral reefs", techniques: ["Light tackle"], baits: ["Sea urchin","Cut bait"], description: "Beautifully colored tropical triggerfish." },
    { name_en: "Barracuda", latin_name: "Sphyraena barracuda", category: "saltwater", habitat: "Tropical reefs worldwide", techniques: ["Casting","Trolling","Fly fishing"], baits: ["Tube lures","Poppers","Needlefish lures"], description: "Fearsome reef predator with razor teeth." },
    { name_en: "Bluefish", latin_name: "Pomatomus saltatrix", category: "saltwater", habitat: "Atlantic coast, worldwide temperate", techniques: ["Casting","Trolling","Surf fishing"], baits: ["Metal lures","Poppers","Cut bait"], description: "Voracious predator of baitfish schools." },
    { name_en: "Common Snook", latin_name: "Centropomus undecimalis", category: "saltwater", habitat: "Florida and Caribbean mangroves", techniques: ["Casting","Fly fishing"], baits: ["Live pilchards","Swimbaits","Flies"], description: "Top inshore game fish. Strictly managed." },
    { name_en: "Fat Snook", latin_name: "Centropomus parallelus", category: "saltwater", habitat: "Florida and Caribbean", techniques: ["Light tackle"], baits: ["Live shrimp","Small lures"], description: "Smaller snook species found in brackish water." },
    { name_en: "Swordspine Snook", latin_name: "Centropomus ensiferus", category: "saltwater", habitat: "Caribbean estuaries", techniques: ["Light tackle"], baits: ["Live shrimp","Small flies"], description: "Smallest snook species." },
    { name_en: "Pacific Halibut", latin_name: "Hippoglossus stenolepis", category: "saltwater", habitat: "North Pacific seafloor", techniques: ["Bottom fishing","Jigging"], baits: ["Large herring","Octopus","Jigs"], description: "Massive flatfish exceeding 400 lbs." },
    { name_en: "California Halibut", latin_name: "Paralichthys californicus", category: "saltwater", habitat: "Eastern Pacific sandy bottoms", techniques: ["Drifting","Jigging"], baits: ["Live anchovies","Swimbaits","Gulp"], description: "Left-eyed flatfish of the West Coast." },
    { name_en: "Atlantic Halibut", latin_name: "Hippoglossus hippoglossus", category: "saltwater", habitat: "North Atlantic seafloor", techniques: ["Bottom fishing"], baits: ["Large cut bait","Squid","Herring"], description: "Largest Atlantic flatfish, very rare." },
    { name_en: "Summer Flounder (Fluke)", latin_name: "Paralichthys dentatus", category: "saltwater", habitat: "Atlantic coast sandy bottoms", techniques: ["Drifting","Jigging","Bucktailing"], baits: ["Minnow/squid combos","Bucktails","Gulp"], description: "Premier flatfish of the Northeast coast." },
    { name_en: "Winter Flounder", latin_name: "Pseudopleuronectes americanus", category: "saltwater", habitat: "Northeast Atlantic bays", techniques: ["Bottom fishing"], baits: ["Bloodworms","Clam","Mussels"], description: "Right-eyed flatfish. Popular spring fishery." },
    { name_en: "Southern Flounder", latin_name: "Paralichthys lethostigma", category: "saltwater", habitat: "South Atlantic and Gulf bays", techniques: ["Gigging","Casting"], baits: ["Live mud minnows","Soft plastics","Gulp"], description: "Largest inshore flounder of the Southeast." },
    { name_en: "Gulf Flounder", latin_name: "Paralichthys albigutta", category: "saltwater", habitat: "Gulf of Mexico bays", techniques: ["Drifting","Bottom fishing"], baits: ["Live shrimp","Soft plastics"], description: "Common Gulf flatfish, smaller than southern flounder." },
    { name_en: "Windowpane Flounder", latin_name: "Scophthalmus aquosus", category: "saltwater", habitat: "Northeast Atlantic sandy bottoms", techniques: ["Bottom fishing"], baits: ["Worms","Squid strips"], description: "Translucent thin-bodied flounder. Mostly released." },
    { name_en: "Hogchoker", latin_name: "Trinectes maculatus", category: "saltwater", habitat: "Atlantic estuaries", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Small sole-like flatfish of East Coast bays." },
    { name_en: "Lingcod", latin_name: "Ophiodon elongatus", category: "saltwater", habitat: "North Pacific, rocky reefs", techniques: ["Jigging","Bottom fishing"], baits: ["Live bait","Large swimbaits","Jigs"], description: "Aggressive Pacific predator with blue-green flesh." },
    { name_en: "Cabezon", latin_name: "Scorpaenichthys marmoratus", category: "saltwater", habitat: "Pacific coast tidepools and reefs", techniques: ["Bottom fishing"], baits: ["Shrimp","Cut bait","Jigs"], description: "Large Pacific sculpin. Toxic roe but excellent flesh." },
    { name_en: "Pacific Cod", latin_name: "Gadus macrocephalus", category: "saltwater", habitat: "North Pacific", techniques: ["Bottom fishing","Jigging"], baits: ["Herring","Squid","Jigs"], description: "Important commercial and sport fish of the Pacific." },
    { name_en: "Atlantic Cod", latin_name: "Gadus morhua", category: "saltwater", habitat: "North Atlantic", techniques: ["Bottom fishing","Jigging"], baits: ["Clam","Jigs","Cut bait"], description: "Historically most important Atlantic fish. Now heavily managed." },
    { name_en: "Haddock", latin_name: "Melanogrammus aeglefinus", category: "saltwater", habitat: "North Atlantic", techniques: ["Bottom fishing","Jigging"], baits: ["Clam","Squid","Jigs"], description: "Popular Northeast groundfish. Distinctive shoulder mark." },
    { name_en: "Pollock", latin_name: "Pollachius virens", category: "saltwater", habitat: "North Atlantic", techniques: ["Jigging","Bottom fishing"], baits: ["Jigs","Cut bait","Soft plastics"], description: "Schooling groundfish of the Northeast. Good fighter." },
    { name_en: "Tilefish (Golden)", latin_name: "Lopholatilus chamaeleonticeps", category: "saltwater", habitat: "Atlantic continental slope", techniques: ["Deep dropping"], baits: ["Squid","Clam","Cut bait"], description: "Deep-water delicacy found in mud burrows." },
    { name_en: "Blueline Tilefish", latin_name: "Caulolatilus microps", category: "saltwater", habitat: "Atlantic, 200-600 ft", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "Mid-depth bottom fish of the Southeast Atlantic." },
    { name_en: "Wreckfish", latin_name: "Polyprion americanus", category: "saltwater", habitat: "Deep Atlantic wrecks", techniques: ["Deep dropping"], baits: ["Large squid","Cut bait"], description: "Massive deep-water fish found around wrecks." },
    { name_en: "Ocean Sunfish (Mola)", latin_name: "Mola mola", category: "saltwater", habitat: "Open ocean worldwide", techniques: ["Not targeted"], baits: ["N/A"], description: "Largest bony fish. Rarely caught intentionally." },
    { name_en: "Opah (Moonfish)", latin_name: "Lampris guttatus", category: "saltwater", habitat: "Deep pelagic worldwide", techniques: ["Deep trolling"], baits: ["Deep lures","Squid"], description: "Only known fully warm-blooded fish. Excellent eating." },
  ];

  // Freshwater species from around the world
  const freshwaterFish = [
    { name_en: "Nile Perch", latin_name: "Lates niloticus", category: "freshwater", habitat: "African great lakes", techniques: ["Trolling","Live bait","Jigging"], baits: ["Large spoons","Live tilapia","Swimbaits"], description: "Massive African predator exceeding 400 lbs." },
    { name_en: "Tigerfish", latin_name: "Hydrocynus vittatus", category: "freshwater", habitat: "African rivers", techniques: ["Spinning","Fly fishing"], baits: ["Spoons","Poppers","Streamers"], description: "Fearsome African predator with razor teeth." },
    { name_en: "Goliath Tigerfish", latin_name: "Hydrocynus goliath", category: "freshwater", habitat: "Congo River basin", techniques: ["Heavy spinning"], baits: ["Large lures","Live bait"], description: "Giant Congo predator reaching 150 lbs." },
    { name_en: "Arapaima", latin_name: "Arapaima gigas", category: "freshwater", habitat: "Amazon basin", techniques: ["Fly fishing","Casting"], baits: ["Large flies","Topwater lures"], description: "World's largest freshwater fish, breathing air." },
    { name_en: "Peacock Bass", latin_name: "Cichla temensis", category: "freshwater", habitat: "Amazon basin, introduced in Florida", techniques: ["Casting","Trolling"], baits: ["Large jerkbaits","Topwater","Jigs"], description: "Powerful tropical predator. Explosive strikes." },
    { name_en: "Golden Dorado", latin_name: "Salminus brasiliensis", category: "freshwater", habitat: "South American rivers", techniques: ["Fly fishing","Spinning"], baits: ["Streamers","Topwater","Spoons"], description: "Golden predator of South American rivers." },
    { name_en: "Payara (Vampire Fish)", latin_name: "Hydrolycus scomberoides", category: "freshwater", habitat: "Amazon and Orinoco basins", techniques: ["Heavy spinning"], baits: ["Deep-diving crankbaits","Spoons"], description: "Fanged predator of fast South American rivers." },
    { name_en: "Pirarucu", latin_name: "Arapaima gigas", category: "freshwater", habitat: "Amazon floodplains", techniques: ["Fly fishing","Casting"], baits: ["Large streamers","Surface lures"], description: "Air-breathing giant of the Amazon." },
    { name_en: "Red-Bellied Piranha", latin_name: "Pygocentrus nattereri", category: "freshwater", habitat: "Amazon and Orinoco basins", techniques: ["Bait fishing"], baits: ["Cut meat","Chicken liver"], description: "Infamous schooling predator of South American rivers." },
    { name_en: "Murray Cod", latin_name: "Maccullochella peelii", category: "freshwater", habitat: "Murray-Darling basin, Australia", techniques: ["Casting","Trolling"], baits: ["Spinnerbaits","Swimbaits","Live yabbies"], description: "Australia's largest freshwater fish." },
    { name_en: "Golden Perch (Yellowbelly)", latin_name: "Macquaria ambigua", category: "freshwater", habitat: "Murray-Darling basin", techniques: ["Casting","Bait fishing"], baits: ["Spinnerbaits","Worms","Shrimp"], description: "Popular Australian native sport fish." },
    { name_en: "Barramundi", latin_name: "Lates calcarifer", category: "freshwater", habitat: "Indo-Pacific estuaries and rivers", techniques: ["Casting","Fly fishing","Trolling"], baits: ["Lures","Poppers","Live bait"], description: "Iconic Australian sport fish that changes sex." },
    { name_en: "Saratoga", latin_name: "Scleropages leichardti", category: "freshwater", habitat: "Northern Australian rivers", techniques: ["Casting","Fly fishing"], baits: ["Surface lures","Flies","Live insects"], description: "Beautiful Australian native related to arowana." },
    { name_en: "Mahseer", latin_name: "Tor putitora", category: "freshwater", habitat: "Himalayan rivers", techniques: ["Spinning","Fly fishing"], baits: ["Spoons","Streamers","Dough balls"], description: "Mighty sport fish of Indian and Asian rivers." },
    { name_en: "Taimen", latin_name: "Hucho taimen", category: "freshwater", habitat: "Siberian and Mongolian rivers", techniques: ["Fly fishing","Spinning"], baits: ["Large streamers","Mice patterns","Spoons"], description: "World's largest salmonid, endangered." },
    { name_en: "Lenok", latin_name: "Brachymystax lenok", category: "freshwater", habitat: "Central Asian rivers", techniques: ["Fly fishing","Spinning"], baits: ["Nymphs","Small streamers","Spinners"], description: "Siberian trout-like species of cold rivers." },
    { name_en: "Arctic Char", latin_name: "Salvelinus alpinus", category: "freshwater", habitat: "Arctic lakes and rivers", techniques: ["Fly fishing","Spinning","Trolling"], baits: ["Spoons","Streamers","Egg patterns"], description: "Northernmost freshwater fish. Beautiful coloring." },
    { name_en: "Dolly Varden", latin_name: "Salvelinus malma", category: "freshwater", habitat: "Pacific Northwest and Alaska streams", techniques: ["Fly fishing","Spinning"], baits: ["Egg patterns","Beads","Small spinners"], description: "Pacific char often found near spawning salmon." },
    { name_en: "Bull Trout", latin_name: "Salvelinus confluentus", category: "freshwater", habitat: "Cold Pacific Northwest rivers", techniques: ["Fly fishing","Spinning"], baits: ["Large streamers","Jigs","Spoons"], description: "Threatened char of the coldest, cleanest rivers." },
    { name_en: "Brook Trout", latin_name: "Salvelinus fontinalis", category: "freshwater", habitat: "Cold Eastern North American streams", techniques: ["Fly fishing","Spinning"], baits: ["Dry flies","Worms","Small spinners"], description: "Native Eastern char with vivid coloring." },
    { name_en: "Lake Trout", latin_name: "Salvelinus namaycush", category: "freshwater", habitat: "Deep cold lakes of North America", techniques: ["Trolling","Jigging","Casting"], baits: ["Large spoons","Tube jigs","Swimbaits"], description: "Deep-lake char reaching 70+ lbs." },
    { name_en: "Splake", latin_name: "Salvelinus fontinalis × namaycush", category: "freshwater", habitat: "Stocked cold lakes", techniques: ["Trolling","Jigging"], baits: ["Spoons","Jigs"], description: "Brook trout × lake trout hybrid." },
    { name_en: "Tiger Trout", latin_name: "Salmo trutta × Salvelinus fontinalis", category: "freshwater", habitat: "Stocked streams and lakes", techniques: ["Fly fishing","Spinning"], baits: ["Streamers","Spinners","Worms"], description: "Brown trout × brook trout hybrid with tiger marks." },
    { name_en: "Golden Trout", latin_name: "Oncorhynchus aguabonita", category: "freshwater", habitat: "High Sierra Nevada streams", techniques: ["Fly fishing","Ultra-light spinning"], baits: ["Small dry flies","Nymphs","Tiny spinners"], description: "Spectacularly colored trout of high elevations." },
    { name_en: "Cutthroat Trout", latin_name: "Oncorhynchus clarkii", category: "freshwater", habitat: "Western North American streams", techniques: ["Fly fishing","Spinning"], baits: ["Dry flies","Nymphs","Spinners"], description: "Native Western trout with red throat slash." },
    { name_en: "Apache Trout", latin_name: "Oncorhynchus apache", category: "freshwater", habitat: "Arizona mountain streams", techniques: ["Fly fishing"], baits: ["Small dry flies","Nymphs"], description: "Endangered trout native to Arizona's White Mountains." },
    { name_en: "Gila Trout", latin_name: "Oncorhynchus gilae", category: "freshwater", habitat: "New Mexico mountain streams", techniques: ["Fly fishing"], baits: ["Small dry flies","Nymphs"], description: "Endangered trout of the Gila River drainage." },
    { name_en: "Atlantic Salmon", latin_name: "Salmo salar", category: "freshwater", habitat: "Atlantic rivers", techniques: ["Fly fishing","Spinning"], baits: ["Salmon flies","Spoons"], description: "King of fly fishing. Anadromous species." },
    { name_en: "Chinook (King) Salmon", latin_name: "Oncorhynchus tshawytscha", category: "freshwater", habitat: "Pacific rivers and Great Lakes", techniques: ["Trolling","Fly fishing","Casting"], baits: ["Spoons","Plugs","Egg patterns"], description: "Largest Pacific salmon, exceeding 100 lbs." },
    { name_en: "Coho (Silver) Salmon", latin_name: "Oncorhynchus kisutch", category: "freshwater", habitat: "Pacific rivers and Great Lakes", techniques: ["Fly fishing","Trolling","Casting"], baits: ["Spoons","Streamers","Spinners"], description: "Acrobatic Pacific salmon. Excellent fighter." },
    { name_en: "Sockeye (Red) Salmon", latin_name: "Oncorhynchus nerka", category: "freshwater", habitat: "Pacific rivers", techniques: ["Fly fishing","Snagging"], baits: ["Small flies","Yarn"], description: "Commercially most important salmon species." },
    { name_en: "Pink (Humpy) Salmon", latin_name: "Oncorhynchus gorbuscha", category: "freshwater", habitat: "Pacific rivers", techniques: ["Fly fishing","Casting"], baits: ["Pink flies","Small spoons"], description: "Smallest and most abundant Pacific salmon." },
    { name_en: "Chum (Dog) Salmon", latin_name: "Oncorhynchus keta", category: "freshwater", habitat: "Pacific rivers", techniques: ["Fly fishing","Casting"], baits: ["Chartreuse flies","Spoons"], description: "Strong Pacific salmon with distinctive teeth." },
    { name_en: "Steelhead", latin_name: "Oncorhynchus mykiss", category: "freshwater", habitat: "Pacific rivers and Great Lakes tributaries", techniques: ["Fly fishing","Float fishing","Casting"], baits: ["Egg patterns","Beads","Spoons","Streamers"], description: "Sea-run rainbow trout. Ultimate river sport fish." },
    { name_en: "Sauger", latin_name: "Sander canadensis", category: "freshwater", habitat: "Central US rivers and reservoirs", techniques: ["Jigging","Trolling"], baits: ["Jigs","Minnows","Crawler harnesses"], description: "Smaller cousin of walleye. Often found in rivers." },
    { name_en: "Saugeye", latin_name: "Sander canadensis × vitreus", category: "freshwater", habitat: "Stocked reservoirs", techniques: ["Jigging","Trolling"], baits: ["Jigs","Crankbaits","Live minnows"], description: "Walleye × sauger hybrid. Aggressive feeder." },
    { name_en: "White Bass", latin_name: "Morone chrysops", category: "freshwater", habitat: "Central US reservoirs and rivers", techniques: ["Casting","Trolling","Jigging"], baits: ["Small jigs","Spoons","Live minnows"], description: "Schooling bass that blitzes surface bait." },
    { name_en: "Hybrid Striped Bass", latin_name: "Morone chrysops × saxatilis", category: "freshwater", habitat: "Stocked reservoirs across US", techniques: ["Casting","Trolling","Live bait"], baits: ["Live shad","Swimbaits","Topwater"], description: "Wiper/sunshine bass. Powerful stocked hybrid." },
    { name_en: "Freshwater Drum", latin_name: "Aplodinotus grunniens", category: "freshwater", habitat: "Central US rivers and lakes", techniques: ["Bottom fishing","Casting"], baits: ["Crawfish","Worms","Jigs"], description: "Only freshwater member of drum family. Makes grunting sounds." },
    { name_en: "Bowfin", latin_name: "Amia calva", category: "freshwater", habitat: "Eastern US swamps and backwaters", techniques: ["Casting","Bait fishing"], baits: ["Cut bait","Topwater","Crawfish"], description: "Living fossil. Aggressive native predator." },
    { name_en: "Longnose Gar", latin_name: "Lepisosteus osseus", category: "freshwater", habitat: "Eastern US rivers and lakes", techniques: ["Casting","Bait fishing"], baits: ["Rope lures","Cut bait","Live minnows"], description: "Armored predator with a long narrow snout." },
    { name_en: "Shortnose Gar", latin_name: "Lepisosteus platostomus", category: "freshwater", habitat: "Mississippi River basin", techniques: ["Casting","Bait fishing"], baits: ["Cut bait","Rope lures"], description: "Smallest gar species of the Mississippi basin." },
    { name_en: "Spotted Gar", latin_name: "Lepisosteus oculatus", category: "freshwater", habitat: "Gulf Coast rivers and lakes", techniques: ["Casting","Bait fishing"], baits: ["Rope lures","Live minnows"], description: "Dark-spotted gar of southern US waters." },
    { name_en: "Florida Gar", latin_name: "Lepisosteus platyrhincus", category: "freshwater", habitat: "Florida lakes and streams", techniques: ["Casting","Bait fishing"], baits: ["Live shiners","Rope lures"], description: "Florida's endemic gar species." },
    { name_en: "Alligator Gar", latin_name: "Atractosteus spatula", category: "freshwater", habitat: "Southern US rivers and reservoirs", techniques: ["Heavy tackle","Bait fishing"], baits: ["Common carp (cut)","Live bait","Rope lures"], description: "North America's largest freshwater fish, exceeding 300 lbs." },
    { name_en: "Paddlefish", latin_name: "Polyodon spathula", category: "freshwater", habitat: "Mississippi River basin reservoirs", techniques: ["Snagging"], baits: ["Snagging hooks (weighted)"], description: "Filter-feeding paddlenose fish. Snagged for sport and caviar." },
    { name_en: "Lake Sturgeon", latin_name: "Acipenser fulvescens", category: "freshwater", habitat: "Great Lakes and large rivers", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish","Cut bait"], description: "Ancient bottom feeder living 100+ years." },
    { name_en: "White Sturgeon", latin_name: "Acipenser transmontanus", category: "freshwater", habitat: "Pacific Northwest rivers", techniques: ["Bottom fishing"], baits: ["Sand shrimp","Smelt","Squid"], description: "North America's largest freshwater fish by weight." },
    { name_en: "Shovelnose Sturgeon", latin_name: "Scaphirhynchus platorynchus", category: "freshwater", habitat: "Missouri and Mississippi rivers", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Flat-nosed sturgeon of muddy rivers." },
    { name_en: "Blue Catfish", latin_name: "Ictalurus furcatus", category: "freshwater", habitat: "Large rivers and reservoirs", techniques: ["Bottom fishing","Drift fishing"], baits: ["Cut shad","Live bait","Punch bait"], description: "Largest North American catfish, exceeding 140 lbs." },
    { name_en: "White Catfish", latin_name: "Ameiurus catus", category: "freshwater", habitat: "Atlantic coast rivers", techniques: ["Bottom fishing"], baits: ["Worms","Chicken liver","Cut bait"], description: "Smaller catfish of coastal rivers." },
    { name_en: "Yellow Bullhead", latin_name: "Ameiurus natalis", category: "freshwater", habitat: "Eastern US ponds and streams", techniques: ["Bottom fishing"], baits: ["Worms","Dough balls"], description: "Common bullhead with white chin barbels." },
    { name_en: "Brown Bullhead", latin_name: "Ameiurus nebulosus", category: "freshwater", habitat: "Eastern US ponds and lakes", techniques: ["Bottom fishing"], baits: ["Worms","Nightcrawlers","Cut bait"], description: "Most common bullhead. Dark mottled coloring." },
    { name_en: "Black Bullhead", latin_name: "Ameiurus melas", category: "freshwater", habitat: "Central US ponds and creeks", techniques: ["Bottom fishing"], baits: ["Worms","Dough balls"], description: "Small bullhead tolerant of poor water quality." },
    { name_en: "Spotted Bass", latin_name: "Micropterus punctulatus", category: "freshwater", habitat: "Central and Southern US streams", techniques: ["Spinning","Fly fishing"], baits: ["Crankbaits","Jigs","Soft plastics"], description: "Aggressive bass preferring current. Rows of spots." },
    { name_en: "Guadalupe Bass", latin_name: "Micropterus treculii", category: "freshwater", habitat: "Central Texas hill country streams", techniques: ["Fly fishing","Spinning"], baits: ["Small crankbaits","Streamers","Crawfish"], description: "Texas state fish. Endemic to Edwards Plateau." },
    { name_en: "Shoal Bass", latin_name: "Micropterus cataractae", category: "freshwater", habitat: "Chattahoochee and Flint river rapids", techniques: ["Fly fishing","Spinning"], baits: ["Crawfish imitations","Small jigs","Nymphs"], description: "Endemic bass of Appalachicola basin shoals." },
    { name_en: "Rock Bass", latin_name: "Ambloplites rupestris", category: "freshwater", habitat: "Eastern US rocky streams and lakes", techniques: ["Light tackle","Fly fishing"], baits: ["Worms","Small jigs","Crickets"], description: "Red-eyed panfish of rocky habitats." },
    { name_en: "Shadow Bass", latin_name: "Ambloplites ariommus", category: "freshwater", habitat: "Southern US clear streams", techniques: ["Light tackle","Fly fishing"], baits: ["Small jigs","Worms","Crawfish"], description: "Smaller cousin of rock bass in southern streams." },
    { name_en: "Ozark Bass", latin_name: "Ambloplites constellatus", category: "freshwater", habitat: "Ozark streams, Missouri/Arkansas", techniques: ["Light tackle"], baits: ["Crickets","Small jigs","Worms"], description: "Ozark endemic bass with star-like markings." },
    { name_en: "Roanoke Bass", latin_name: "Ambloplites cavifrons", category: "freshwater", habitat: "Roanoke River drainage, Virginia", techniques: ["Light tackle","Fly fishing"], baits: ["Crawfish","Worms","Small poppers"], description: "Rare bass of Virginia's Roanoke drainage." },
    { name_en: "Green Sunfish", latin_name: "Lepomis cyanellus", category: "freshwater", habitat: "Throughout US streams and ponds", techniques: ["Light tackle","Fly fishing"], baits: ["Worms","Crickets","Small poppers"], description: "Hardy sunfish found in many small waters." },
    { name_en: "Longear Sunfish", latin_name: "Lepomis megalotis", category: "freshwater", habitat: "Central US streams", techniques: ["Light tackle","Fly fishing"], baits: ["Worms","Small flies","Crickets"], description: "Colorful sunfish with long opercular flap." },
    { name_en: "Orangespotted Sunfish", latin_name: "Lepomis humilis", category: "freshwater", habitat: "Central US streams and ponds", techniques: ["Micro fishing","Light tackle"], baits: ["Tiny worms","Bread"], description: "Small sunfish with orange spots." },
    { name_en: "Dollar Sunfish", latin_name: "Lepomis marginatus", category: "freshwater", habitat: "Southeastern US coastal plain", techniques: ["Light tackle"], baits: ["Worms","Crickets"], description: "Small silvery sunfish of southern streams." },
    { name_en: "Bantam Sunfish", latin_name: "Lepomis symmetricus", category: "freshwater", habitat: "Gulf coast swamps", techniques: ["Micro fishing"], baits: ["Tiny worms"], description: "Small secretive sunfish of southern swamps." },
    { name_en: "Warmouth", latin_name: "Lepomis gulosus", category: "freshwater", habitat: "Eastern US swamps and ponds", techniques: ["Light tackle","Bait fishing"], baits: ["Worms","Crickets","Small jigs"], description: "Large-mouthed sunfish of dark swampy waters." },
    { name_en: "Flier Sunfish", latin_name: "Centrarchus macropterus", category: "freshwater", habitat: "Southeastern US swamps", techniques: ["Light tackle"], baits: ["Worms","Crickets","Small flies"], description: "Deep-bodied sunfish with spotted fins." },
    { name_en: "Sacramento Perch", latin_name: "Archoplites interruptus", category: "freshwater", habitat: "California (introduced populations)", techniques: ["Bait fishing","Light tackle"], baits: ["Worms","Small jigs"], description: "Only native sunfish west of the Rockies." },
    { name_en: "White Crappie", latin_name: "Pomoxis annularis", category: "freshwater", habitat: "US lakes and reservoirs", techniques: ["Jigging","Float fishing"], baits: ["Minnows","Small jigs","Tubes"], description: "Schooling panfish preferring murkier waters." },
    { name_en: "Black Crappie", latin_name: "Pomoxis nigromaculatus", category: "freshwater", habitat: "US clear lakes and reservoirs", techniques: ["Jigging","Float fishing"], baits: ["Minnows","Small jigs","Tubes"], description: "Spotted crappie preferring clearer water." },
    { name_en: "Chain Pickerel", latin_name: "Esox niger", category: "freshwater", habitat: "Eastern US lakes and rivers", techniques: ["Casting","Trolling"], baits: ["Spinnerbaits","Live minnows","Spoons"], description: "Chain-patterned pickerel. Aggressive striker." },
    { name_en: "Grass Pickerel", latin_name: "Esox americanus vermiculatus", category: "freshwater", habitat: "Eastern US weedy streams", techniques: ["Light tackle"], baits: ["Small spinners","Live minnows"], description: "Smallest pike family member. Found in weedy streams." },
    { name_en: "Redfin Pickerel", latin_name: "Esox americanus americanus", category: "freshwater", habitat: "Atlantic coast streams", techniques: ["Light tackle"], baits: ["Small spinners","Worms","Live minnows"], description: "Small pickerel of coastal streams." },
    { name_en: "Tiger Muskie", latin_name: "Esox masquinongy × lucius", category: "freshwater", habitat: "Stocked lakes and reservoirs", techniques: ["Casting","Trolling"], baits: ["Large lures","Swimbaits","Bucktails"], description: "Muskie × pike hybrid. Tiger-striped and aggressive." },
    { name_en: "Cisco (Lake Herring)", latin_name: "Coregonus artedi", category: "freshwater", habitat: "Great Lakes and northern lakes", techniques: ["Ice fishing","Jigging"], baits: ["Small jigs","Wax worms"], description: "Important forage fish also targeted by anglers." },
    { name_en: "Lake Whitefish", latin_name: "Coregonus clupeaformis", category: "freshwater", habitat: "Great Lakes and deep northern lakes", techniques: ["Bottom fishing","Ice fishing"], baits: ["Spawn bags","Worms","Small jigs"], description: "Valued commercial and sport fish." },
    { name_en: "Mountain Whitefish", latin_name: "Prosopium williamsoni", category: "freshwater", habitat: "Western US cold rivers", techniques: ["Fly fishing","Bait fishing"], baits: ["Nymphs","Worms","Small flies"], description: "Common Western fish often caught while trout fishing." },
    { name_en: "Round Whitefish", latin_name: "Prosopium cylindraceum", category: "freshwater", habitat: "Northern US and Canadian lakes", techniques: ["Bottom fishing"], baits: ["Worms","Small jigs"], description: "Cylindrical whitefish of cold northern waters." },
    { name_en: "Inconnu (Sheefish)", latin_name: "Stenodus leucichthys", category: "freshwater", habitat: "Alaska and Yukon rivers", techniques: ["Casting","Fly fishing"], baits: ["Spoons","Streamers","Jigs"], description: "Largest whitefish. Predatory and hard-fighting." },
    { name_en: "Burbot", latin_name: "Lota lota", category: "freshwater", habitat: "Deep cold lakes and rivers", techniques: ["Ice fishing","Bottom fishing"], baits: ["Cut bait","Glow jigs","Live minnows"], description: "Only freshwater cod. Excellent winter target." },
    { name_en: "American Eel", latin_name: "Anguilla rostrata", category: "freshwater", habitat: "Atlantic coast rivers and estuaries", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait","Live bait"], description: "Catadromous fish migrating to Sargasso Sea to spawn." },
    { name_en: "Common Carp", latin_name: "Cyprinus carpio", category: "freshwater", habitat: "Lakes and rivers worldwide", techniques: ["Bottom fishing","Carp fishing"], baits: ["Boilies","Corn","Dough balls","Bread"], description: "Powerful non-native fish. Growing sport fishing culture." },
    { name_en: "Grass Carp", latin_name: "Ctenopharyngodon idella", category: "freshwater", habitat: "Stocked lakes for vegetation control", techniques: ["Float fishing"], baits: ["Grass","Bread","Corn"], description: "Herbivorous carp stocked to control aquatic plants." },
    { name_en: "Bighead Carp", latin_name: "Hypophthalmichthys nobilis", category: "freshwater", habitat: "Mississippi basin (invasive)", techniques: ["Bow fishing","Snagging"], baits: ["Plankton-based (snagged)"], description: "Invasive Asian carp. Filter feeder." },
    { name_en: "Silver Carp", latin_name: "Hypophthalmichthys molitrix", category: "freshwater", habitat: "Mississippi basin (invasive)", techniques: ["Bow fishing"], baits: ["Snagged or bow-fished"], description: "Invasive leaping carp. Hazard to boaters." },
    { name_en: "Black Carp", latin_name: "Mylopharyngodon piceus", category: "freshwater", habitat: "Mississippi basin (rare invasive)", techniques: ["Bottom fishing"], baits: ["Mussels","Snails"], description: "Mollusk-eating invasive carp. Very rare catch." },
    { name_en: "Goldfish (Wild)", latin_name: "Carassius auratus", category: "freshwater", habitat: "Ponds and slow waters (released populations)", techniques: ["Float fishing"], baits: ["Bread","Corn","Worms"], description: "Released pet fish now established in many waters." },
    { name_en: "Quillback Carpsucker", latin_name: "Carpiodes cyprinus", category: "freshwater", habitat: "Central US rivers and lakes", techniques: ["Bottom fishing"], baits: ["Worms","Dough balls"], description: "Native sucker with a long dorsal fin ray." },
    { name_en: "River Carpsucker", latin_name: "Carpiodes carpio", category: "freshwater", habitat: "Mississippi River basin", techniques: ["Bottom fishing"], baits: ["Worms","Dough balls"], description: "Common sucker of large river systems." },
    { name_en: "Smallmouth Buffalo", latin_name: "Ictiobus bubalus", category: "freshwater", habitat: "Central US rivers and reservoirs", techniques: ["Bottom fishing","Bow fishing"], baits: ["Dough balls","Worms","Corn"], description: "Large native sucker reaching 80+ lbs." },
    { name_en: "Bigmouth Buffalo", latin_name: "Ictiobus cyprinellus", category: "freshwater", habitat: "Central US rivers and lakes", techniques: ["Bottom fishing","Bow fishing"], baits: ["Corn","Dough balls"], description: "Largest native sucker. Can live over 100 years." },
    { name_en: "Black Buffalo", latin_name: "Ictiobus niger", category: "freshwater", habitat: "Mississippi basin rivers", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Dark-colored buffalo sucker of deep rivers." },
    { name_en: "White Sucker", latin_name: "Catostomus commersonii", category: "freshwater", habitat: "Throughout North American streams", techniques: ["Bottom fishing"], baits: ["Worms","Maggots"], description: "Common sucker running up streams in spring." },
    { name_en: "Longnose Sucker", latin_name: "Catostomus catostomus", category: "freshwater", habitat: "Northern US and Canadian rivers", techniques: ["Bottom fishing"], baits: ["Worms","Small jigs"], description: "Long-nosed sucker of cold northern waters." },
    { name_en: "Hog Sucker", latin_name: "Hypentelium nigricans", category: "freshwater", habitat: "Eastern US clear streams", techniques: ["Bottom fishing"], baits: ["Worms","Maggots"], description: "Bottom-dwelling sucker of clear rocky streams." },
    { name_en: "Redhorse (Golden)", latin_name: "Moxostoma erythrurum", category: "freshwater", habitat: "Eastern US rivers", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish tails"], description: "Golden-colored native sucker." },
    { name_en: "Redhorse (Shorthead)", latin_name: "Moxostoma macrolepidotum", category: "freshwater", habitat: "Eastern US rivers and lakes", techniques: ["Bottom fishing"], baits: ["Worms","Maggots"], description: "Common redhorse of moderate-sized rivers." },
    { name_en: "River Redhorse", latin_name: "Moxostoma carinatum", category: "freshwater", habitat: "Eastern US large rivers", techniques: ["Bottom fishing"], baits: ["Crawfish tails","Worms"], description: "Large redhorse with molar-like teeth." },
    { name_en: "Greater Redhorse", latin_name: "Moxostoma valenciennesi", category: "freshwater", habitat: "Great Lakes tributaries", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish"], description: "Largest redhorse species." },
    { name_en: "Spotted Sucker", latin_name: "Minytrema melanops", category: "freshwater", habitat: "Eastern US rivers", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Dark-spotted sucker of clear streams." },
    { name_en: "Blue Sucker", latin_name: "Cycleptus elongatus", category: "freshwater", habitat: "Mississippi basin large rivers", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Elongated sucker of swift large rivers." },
    { name_en: "Creek Chub", latin_name: "Semotilus atromaculatus", category: "freshwater", habitat: "Eastern US small streams", techniques: ["Micro fishing","Light tackle"], baits: ["Worms","Bread","Small flies"], description: "Common creek fish. Popular live bait." },
    { name_en: "Hornyhead Chub", latin_name: "Nocomis biguttatus", category: "freshwater", habitat: "Central US streams", techniques: ["Micro fishing"], baits: ["Worms","Bread"], description: "Nest-building chub of clear streams." },
    { name_en: "River Chub", latin_name: "Nocomis micropogon", category: "freshwater", habitat: "Eastern US rivers", techniques: ["Micro fishing"], baits: ["Worms","Bread"], description: "Large chub that builds impressive gravel nests." },
    { name_en: "Fallfish", latin_name: "Semotilus corporalis", category: "freshwater", habitat: "Northeast US streams", techniques: ["Light tackle","Fly fishing"], baits: ["Worms","Small flies","Bread"], description: "Largest native Eastern minnow. Spirited fighter." },
    { name_en: "Golden Shiner", latin_name: "Notemigonus crysoleucas", category: "freshwater", habitat: "Throughout Eastern US", techniques: ["Micro fishing"], baits: ["Bread","Tiny worms"], description: "Most important bait fish. Also caught for fun." },
    { name_en: "Mooneye", latin_name: "Hiodon tergisus", category: "freshwater", habitat: "Central US clear rivers", techniques: ["Fly fishing","Light tackle"], baits: ["Small flies","Tiny jigs"], description: "Silvery river fish with large eye." },
    { name_en: "Goldeye", latin_name: "Hiodon alosoides", category: "freshwater", habitat: "Northern US and Canadian rivers", techniques: ["Fly fishing","Light tackle"], baits: ["Small flies","Tiny spinners"], description: "Golden-eyed river fish. Popular smoked." },
    { name_en: "Freshwater Goby (Round)", latin_name: "Neogobius melanostomus", category: "freshwater", habitat: "Great Lakes (invasive)", techniques: ["Micro fishing"], baits: ["Worms","Small jigs"], description: "Invasive bottom-dwelling goby now common in Great Lakes." },
  ];

  species.push(...saltwaterFish, ...freshwaterFish);
  return species;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Get existing names
    const { data: existing } = await supabase.from("fish_species").select("name_en");
    const existingNames = new Set((existing || []).map((f: any) => f.name_en.toLowerCase()));

    const allFish = generateFishSpecies();
    const newFish = allFish.filter(f => !existingNames.has(f.name_en.toLowerCase()));

    let inserted = 0;
    const batchSize = 50;
    for (let i = 0; i < newFish.length; i += batchSize) {
      const batch = newFish.slice(i, i + batchSize);
      const { error } = await supabase.from("fish_species").insert(batch);
      if (!error) inserted += batch.length;
    }

    return new Response(
      JSON.stringify({ success: true, total_new: newFish.length, inserted }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
