import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const moreLocations = [
  // ALASKA
  { name: "Kenai River – Upper", lat: 60.49, lng: -149.77, category: "river", state: "Alaska", species: ["Sockeye Salmon","Rainbow Trout","Dolly Varden"] },
  { name: "Kenai River – Lower", lat: 60.54, lng: -151.10, category: "river", state: "Alaska", species: ["King Salmon","Silver Salmon","Rainbow Trout"] },
  { name: "Russian River", lat: 60.47, lng: -149.95, category: "river", state: "Alaska", species: ["Sockeye Salmon","Rainbow Trout"] },
  { name: "Kasilof River", lat: 60.34, lng: -151.30, category: "river", state: "Alaska", species: ["King Salmon","Silver Salmon","Steelhead"] },
  { name: "Anchor River", lat: 59.78, lng: -151.82, category: "river", state: "Alaska", species: ["King Salmon","Steelhead","Dolly Varden"] },
  { name: "Resurrection Bay", lat: 60.10, lng: -149.43, category: "bay", state: "Alaska", species: ["Halibut","Silver Salmon","Lingcod"] },
  { name: "Ship Creek – Anchorage", lat: 61.22, lng: -149.88, category: "stream", state: "Alaska", species: ["King Salmon","Silver Salmon","Pink Salmon"] },
  { name: "Lake Clark", lat: 60.20, lng: -154.32, category: "lake", state: "Alaska", species: ["Rainbow Trout","Northern Pike","Lake Trout"] },
  { name: "Bristol Bay – Naknek", lat: 58.73, lng: -157.01, category: "bay", state: "Alaska", species: ["Sockeye Salmon","King Salmon","Rainbow Trout"] },
  { name: "Situk River", lat: 59.48, lng: -139.63, category: "river", state: "Alaska", species: ["Steelhead","Silver Salmon","Sockeye Salmon"] },

  // HAWAII
  { name: "Wahiawa Reservoir", lat: 21.50, lng: -158.02, category: "reservoir", state: "Hawaii", species: ["Largemouth Bass","Peacock Bass","Tilapia"] },
  { name: "Lake Wilson", lat: 21.51, lng: -158.03, category: "lake", state: "Hawaii", species: ["Largemouth Bass","Peacock Bass","Channel Catfish"] },
  { name: "Kona Coast", lat: 19.64, lng: -156.00, category: "bay", state: "Hawaii", species: ["Blue Marlin","Yellowfin Tuna","Mahi-Mahi"] },

  // MORE NORTHEAST
  { name: "Housatonic River", lat: 41.77, lng: -73.30, category: "river", state: "Connecticut", species: ["Brown Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Farmington River", lat: 41.85, lng: -72.95, category: "river", state: "Connecticut", species: ["Brown Trout","Rainbow Trout","Atlantic Salmon"] },
  { name: "Thames River", lat: 41.45, lng: -72.10, category: "river", state: "Connecticut", species: ["Striped Bass","Bluefish","White Perch"] },
  { name: "Candlewood Lake", lat: 41.47, lng: -73.53, category: "lake", state: "Connecticut", species: ["Largemouth Bass","Smallmouth Bass","Walleye"] },
  { name: "Lake Lillinonah", lat: 41.42, lng: -73.23, category: "reservoir", state: "Connecticut", species: ["Largemouth Bass","Crappie","Walleye"] },
  { name: "Battenkill River", lat: 43.07, lng: -73.28, category: "river", state: "Vermont/New York", species: ["Brown Trout","Brook Trout","Rainbow Trout"] },
  { name: "Otter Creek", lat: 43.60, lng: -73.17, category: "river", state: "Vermont", species: ["Smallmouth Bass","Northern Pike","Walleye"] },
  { name: "Lake Memphremagog", lat: 44.95, lng: -72.22, category: "lake", state: "Vermont", species: ["Lake Trout","Landlocked Salmon","Smallmouth Bass"] },
  { name: "Quabbin Reservoir", lat: 42.40, lng: -72.32, category: "reservoir", state: "Massachusetts", species: ["Lake Trout","Smallmouth Bass","Landlocked Salmon"] },
  { name: "Wachusett Reservoir", lat: 42.40, lng: -71.72, category: "reservoir", state: "Massachusetts", species: ["Lake Trout","Smallmouth Bass","Largemouth Bass"] },
  { name: "Cape Cod Canal", lat: 41.74, lng: -70.58, category: "bay", state: "Massachusetts", species: ["Striped Bass","Bluefish","Tautog"] },
  { name: "Stellwagen Bank", lat: 42.30, lng: -70.35, category: "bay", state: "Massachusetts", species: ["Bluefin Tuna","Striped Bass","Cod"] },
  { name: "Merrimack River", lat: 42.77, lng: -71.08, category: "river", state: "Massachusetts/New Hampshire", species: ["Striped Bass","Shad","Smallmouth Bass"] },
  { name: "Lake Winnipesaukee", lat: 43.57, lng: -71.30, category: "lake", state: "New Hampshire", species: ["Lake Trout","Landlocked Salmon","Smallmouth Bass"] },
  { name: "Lake Sunapee", lat: 43.38, lng: -72.05, category: "lake", state: "New Hampshire", species: ["Lake Trout","Landlocked Salmon","Rainbow Trout"] },
  { name: "Androscoggin River", lat: 44.48, lng: -71.17, category: "river", state: "New Hampshire", species: ["Brown Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Kennebago River", lat: 44.97, lng: -70.82, category: "river", state: "Maine", species: ["Brook Trout","Landlocked Salmon"] },
  { name: "Moosehead Lake", lat: 45.60, lng: -69.65, category: "lake", state: "Maine", species: ["Lake Trout","Landlocked Salmon","Brook Trout"] },
  { name: "Penobscot River", lat: 44.80, lng: -68.77, category: "river", state: "Maine", species: ["Atlantic Salmon","Smallmouth Bass","Striped Bass"] },
  { name: "Grand Lake Stream", lat: 45.18, lng: -67.78, category: "stream", state: "Maine", species: ["Landlocked Salmon","Smallmouth Bass","Brook Trout"] },
  { name: "Rapid River", lat: 44.82, lng: -70.88, category: "river", state: "Maine", species: ["Brook Trout","Landlocked Salmon"] },
  { name: "Narragansett Bay", lat: 41.62, lng: -71.37, category: "bay", state: "Rhode Island", species: ["Striped Bass","Bluefish","Tautog","Scup"] },
  { name: "Block Island", lat: 41.17, lng: -71.58, category: "bay", state: "Rhode Island", species: ["Striped Bass","Bluefish","Fluke","Black Sea Bass"] },

  // MORE MID-ATLANTIC
  { name: "Montauk Point", lat: 41.07, lng: -71.86, category: "bay", state: "New York", species: ["Striped Bass","Bluefish","Fluke","Tuna"] },
  { name: "Finger Lakes – Seneca", lat: 42.67, lng: -76.92, category: "lake", state: "New York", species: ["Lake Trout","Rainbow Trout","Brown Trout","Smallmouth Bass"] },
  { name: "Finger Lakes – Cayuga", lat: 42.72, lng: -76.72, category: "lake", state: "New York", species: ["Lake Trout","Rainbow Trout","Largemouth Bass"] },
  { name: "Finger Lakes – Keuka", lat: 42.55, lng: -77.10, category: "lake", state: "New York", species: ["Lake Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Ausable River – NY", lat: 44.45, lng: -73.58, category: "river", state: "New York", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Salmon River – NY", lat: 43.52, lng: -75.95, category: "river", state: "New York", species: ["Chinook Salmon","Steelhead","Brown Trout"] },
  { name: "Niagara River", lat: 43.07, lng: -79.07, category: "river", state: "New York", species: ["Smallmouth Bass","Steelhead","Lake Trout","Muskellunge"] },
  { name: "Lake George", lat: 43.42, lng: -73.70, category: "lake", state: "New York", species: ["Lake Trout","Landlocked Salmon","Largemouth Bass"] },
  { name: "Oneida Lake", lat: 43.20, lng: -75.92, category: "lake", state: "New York", species: ["Walleye","Smallmouth Bass","Yellow Perch"] },
  { name: "Peconic Bay", lat: 41.05, lng: -72.38, category: "bay", state: "New York", species: ["Striped Bass","Fluke","Weakfish","Bluefish"] },
  { name: "Spruce Creek", lat: 40.58, lng: -78.13, category: "stream", state: "Pennsylvania", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Penns Creek", lat: 40.87, lng: -77.15, category: "stream", state: "Pennsylvania", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Letort Spring Run", lat: 40.18, lng: -77.22, category: "stream", state: "Pennsylvania", species: ["Brown Trout","Brook Trout"] },
  { name: "Yellow Breeches Creek", lat: 40.12, lng: -77.00, category: "stream", state: "Pennsylvania", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Lake Wallenpaupack", lat: 41.38, lng: -75.20, category: "lake", state: "Pennsylvania", species: ["Walleye","Smallmouth Bass","Striped Bass"] },
  { name: "Raystown Lake", lat: 40.40, lng: -78.02, category: "reservoir", state: "Pennsylvania", species: ["Striped Bass","Largemouth Bass","Walleye"] },
  { name: "Pine Creek – PA", lat: 41.50, lng: -77.45, category: "stream", state: "Pennsylvania", species: ["Brown Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Barnegat Bay", lat: 39.78, lng: -74.12, category: "bay", state: "New Jersey", species: ["Striped Bass","Bluefish","Fluke","Weakfish"] },
  { name: "Round Valley Reservoir", lat: 40.62, lng: -74.85, category: "reservoir", state: "New Jersey", species: ["Lake Trout","Brown Trout","Smallmouth Bass"] },
  { name: "Manasquan Reservoir", lat: 40.18, lng: -74.28, category: "reservoir", state: "New Jersey", species: ["Largemouth Bass","Hybrid Striped Bass","Crappie"] },
  { name: "Chesapeake Bay – Upper", lat: 39.22, lng: -76.28, category: "bay", state: "Maryland", species: ["Striped Bass","White Perch","Blue Catfish"] },
  { name: "Chesapeake Bay – Lower", lat: 37.25, lng: -76.10, category: "bay", state: "Virginia", species: ["Striped Bass","Speckled Trout","Red Drum"] },
  { name: "Deep Creek Lake", lat: 39.52, lng: -79.32, category: "lake", state: "Maryland", species: ["Largemouth Bass","Walleye","Yellow Perch"] },
  { name: "Gunpowder Falls", lat: 39.47, lng: -76.63, category: "stream", state: "Maryland", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Savage River", lat: 39.52, lng: -79.10, category: "river", state: "Maryland", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },

  // MORE SOUTHEAST
  { name: "Lake Jocassee", lat: 34.95, lng: -82.92, category: "reservoir", state: "South Carolina", species: ["Brown Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Lake Murray – SC", lat: 34.05, lng: -81.25, category: "reservoir", state: "South Carolina", species: ["Striped Bass","Largemouth Bass","Crappie"] },
  { name: "Santee Cooper Lakes", lat: 33.45, lng: -80.12, category: "reservoir", state: "South Carolina", species: ["Striped Bass","Largemouth Bass","Catfish"] },
  { name: "Chattooga River", lat: 34.82, lng: -83.32, category: "river", state: "South Carolina/Georgia", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Edisto River", lat: 33.05, lng: -80.52, category: "river", state: "South Carolina", species: ["Redbreast Sunfish","Largemouth Bass","Catfish"] },
  { name: "Cape Fear River", lat: 34.08, lng: -78.88, category: "river", state: "North Carolina", species: ["Largemouth Bass","Catfish","Striped Bass"] },
  { name: "New River – NC", lat: 36.38, lng: -81.48, category: "river", state: "North Carolina", species: ["Smallmouth Bass","Muskellunge","Rock Bass"] },
  { name: "Lake Norman", lat: 35.45, lng: -80.95, category: "reservoir", state: "North Carolina", species: ["Largemouth Bass","Striped Bass","Catfish"] },
  { name: "Fontana Lake", lat: 35.42, lng: -83.72, category: "reservoir", state: "North Carolina", species: ["Smallmouth Bass","Walleye","Brown Trout"] },
  { name: "Nantahala River", lat: 35.32, lng: -83.58, category: "river", state: "North Carolina", species: ["Rainbow Trout","Brown Trout","Brook Trout"] },
  { name: "Davidson River", lat: 35.28, lng: -82.72, category: "river", state: "North Carolina", species: ["Rainbow Trout","Brown Trout","Brook Trout"] },
  { name: "Outer Banks – Oregon Inlet", lat: 35.77, lng: -75.55, category: "bay", state: "North Carolina", species: ["Red Drum","Bluefish","Flounder","Cobia"] },
  { name: "Pamlico Sound", lat: 35.28, lng: -76.17, category: "bay", state: "North Carolina", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Mosquito Lagoon", lat: 28.82, lng: -80.77, category: "bay", state: "Florida", species: ["Red Drum","Spotted Seatrout","Black Drum"] },
  { name: "Indian River Lagoon", lat: 27.80, lng: -80.48, category: "bay", state: "Florida", species: ["Snook","Red Drum","Spotted Seatrout"] },
  { name: "Tampa Bay", lat: 27.75, lng: -82.55, category: "bay", state: "Florida", species: ["Snook","Red Drum","Spotted Seatrout","Tarpon"] },
  { name: "Charlotte Harbor", lat: 26.87, lng: -82.10, category: "bay", state: "Florida", species: ["Snook","Tarpon","Red Drum","Spotted Seatrout"] },
  { name: "Biscayne Bay", lat: 25.58, lng: -80.22, category: "bay", state: "Florida", species: ["Bonefish","Tarpon","Permit","Snook"] },
  { name: "Florida Keys – Islamorada", lat: 24.92, lng: -80.63, category: "bay", state: "Florida", species: ["Tarpon","Bonefish","Permit","Snook"] },
  { name: "Florida Keys – Key West", lat: 24.55, lng: -81.78, category: "bay", state: "Florida", species: ["Tarpon","Barracuda","Permit","Yellowtail Snapper"] },
  { name: "Lake Toho", lat: 28.22, lng: -81.42, category: "lake", state: "Florida", species: ["Largemouth Bass","Bluegill","Crappie"] },
  { name: "Lake Istokpoga", lat: 27.38, lng: -81.25, category: "lake", state: "Florida", species: ["Largemouth Bass","Crappie","Bluegill"] },
  { name: "Stick Marsh / Farm 13", lat: 27.72, lng: -80.68, category: "reservoir", state: "Florida", species: ["Largemouth Bass","Bluegill","Crappie"] },
  { name: "Rodman Reservoir", lat: 29.48, lng: -81.82, category: "reservoir", state: "Florida", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Apalachicola River", lat: 29.95, lng: -85.02, category: "river", state: "Florida", species: ["Largemouth Bass","Striped Bass","Catfish"] },
  { name: "Suwannee River – FL", lat: 29.55, lng: -83.18, category: "river", state: "Florida", species: ["Largemouth Bass","Suwannee Bass","Catfish"] },
  { name: "Everglades – L-67A Canal", lat: 25.82, lng: -80.62, category: "stream", state: "Florida", species: ["Largemouth Bass","Peacock Bass","Mayan Cichlid"] },
  { name: "Lake Eufaula – AL", lat: 31.92, lng: -85.08, category: "reservoir", state: "Alabama", species: ["Largemouth Bass","Crappie","Striped Bass"] },
  { name: "Lewis Smith Lake", lat: 34.08, lng: -87.12, category: "reservoir", state: "Alabama", species: ["Spotted Bass","Striped Bass","Walleye"] },
  { name: "Pickwick Lake – AL", lat: 34.78, lng: -87.92, category: "reservoir", state: "Alabama", species: ["Smallmouth Bass","Largemouth Bass","Catfish"] },
  { name: "Lake Guntersville", lat: 34.38, lng: -86.32, category: "reservoir", state: "Alabama", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Mobile-Tensaw Delta", lat: 30.72, lng: -87.95, category: "river", state: "Alabama", species: ["Largemouth Bass","Red Drum","Speckled Trout"] },
  { name: "Ross Barnett Reservoir", lat: 32.42, lng: -89.95, category: "reservoir", state: "Mississippi", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Grenada Lake", lat: 33.78, lng: -89.78, category: "reservoir", state: "Mississippi", species: ["Crappie","Largemouth Bass","Catfish"] },
  { name: "Sardis Lake", lat: 34.38, lng: -89.78, category: "reservoir", state: "Mississippi", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Mississippi Gulf Coast", lat: 30.37, lng: -89.08, category: "bay", state: "Mississippi", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Toledo Bend Reservoir", lat: 31.18, lng: -93.58, category: "reservoir", state: "Louisiana/Texas", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Atchafalaya Basin", lat: 30.28, lng: -91.82, category: "river", state: "Louisiana", species: ["Largemouth Bass","Crappie","Catfish","Bowfin"] },
  { name: "Lake Pontchartrain", lat: 30.22, lng: -90.12, category: "lake", state: "Louisiana", species: ["Speckled Trout","Red Drum","Flounder"] },
  { name: "Venice – Louisiana", lat: 29.28, lng: -89.35, category: "bay", state: "Louisiana", species: ["Red Drum","Speckled Trout","Tarpon","Tuna"] },
  { name: "Grand Isle", lat: 29.23, lng: -90.00, category: "bay", state: "Louisiana", species: ["Red Drum","Speckled Trout","Cobia","Tarpon"] },
  { name: "Calcasieu Lake", lat: 29.97, lng: -93.32, category: "lake", state: "Louisiana", species: ["Speckled Trout","Red Drum","Flounder"] },
  { name: "Sabine Lake", lat: 29.88, lng: -93.88, category: "lake", state: "Texas/Louisiana", species: ["Speckled Trout","Red Drum","Flounder"] },

  // MORE TEXAS
  { name: "Lake Fork", lat: 32.82, lng: -95.58, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Sam Rayburn Reservoir", lat: 31.08, lng: -94.15, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Lake Conroe", lat: 30.38, lng: -95.55, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Catfish","Crappie","Hybrid Striped Bass"] },
  { name: "Lake Livingston", lat: 30.72, lng: -95.02, category: "reservoir", state: "Texas", species: ["White Bass","Catfish","Crappie"] },
  { name: "Falcon Lake", lat: 26.55, lng: -99.18, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Catfish","White Bass"] },
  { name: "Choke Canyon Reservoir", lat: 28.48, lng: -98.35, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Catfish","White Bass"] },
  { name: "Lake O.H. Ivie", lat: 31.55, lng: -99.68, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Smallmouth Bass","Crappie"] },
  { name: "Lake Amistad", lat: 29.45, lng: -101.08, category: "reservoir", state: "Texas", species: ["Largemouth Bass","Smallmouth Bass","Striped Bass","Catfish"] },
  { name: "Port Aransas", lat: 27.83, lng: -97.05, category: "bay", state: "Texas", species: ["Red Drum","Speckled Trout","Tarpon","King Mackerel"] },
  { name: "Galveston Bay", lat: 29.50, lng: -94.88, category: "bay", state: "Texas", species: ["Speckled Trout","Red Drum","Flounder","Sheepshead"] },
  { name: "Matagorda Bay", lat: 28.58, lng: -96.32, category: "bay", state: "Texas", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Laguna Madre – Upper", lat: 27.18, lng: -97.38, category: "bay", state: "Texas", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Laguna Madre – Lower", lat: 26.28, lng: -97.32, category: "bay", state: "Texas", species: ["Red Drum","Speckled Trout","Snook"] },
  { name: "Guadalupe River", lat: 29.85, lng: -98.22, category: "river", state: "Texas", species: ["Guadalupe Bass","Largemouth Bass","Catfish"] },
  { name: "Devil's River", lat: 29.88, lng: -100.85, category: "river", state: "Texas", species: ["Smallmouth Bass","Largemouth Bass","Channel Catfish"] },
  { name: "Colorado River – TX", lat: 30.28, lng: -97.75, category: "river", state: "Texas", species: ["Largemouth Bass","Catfish","Sunfish"] },

  // MORE MIDWEST
  { name: "Lake Erie – Western Basin", lat: 41.55, lng: -82.88, category: "lake", state: "Ohio", species: ["Walleye","Yellow Perch","Smallmouth Bass","Steelhead"] },
  { name: "Lake Erie – Central Basin", lat: 41.65, lng: -81.58, category: "lake", state: "Ohio", species: ["Walleye","Steelhead","Smallmouth Bass"] },
  { name: "Clear Fork Reservoir", lat: 40.62, lng: -82.48, category: "reservoir", state: "Ohio", species: ["Muskellunge","Crappie","Largemouth Bass"] },
  { name: "Piedmont Lake", lat: 40.15, lng: -81.23, category: "reservoir", state: "Ohio", species: ["Muskellunge","Largemouth Bass","Crappie"] },
  { name: "Grand River – OH", lat: 41.75, lng: -81.28, category: "river", state: "Ohio", species: ["Steelhead","Smallmouth Bass","Channel Catfish"] },
  { name: "Mad River – OH", lat: 40.02, lng: -83.88, category: "river", state: "Ohio", species: ["Brown Trout","Rainbow Trout","Smallmouth Bass"] },
  { name: "Lake Michigan – Ludington", lat: 43.95, lng: -86.45, category: "lake", state: "Michigan", species: ["Chinook Salmon","Steelhead","Lake Trout","Brown Trout"] },
  { name: "Lake Michigan – Manistee", lat: 44.25, lng: -86.35, category: "lake", state: "Michigan", species: ["Chinook Salmon","Steelhead","Lake Trout"] },
  { name: "Pere Marquette River", lat: 43.92, lng: -86.02, category: "river", state: "Michigan", species: ["Steelhead","Chinook Salmon","Brown Trout"] },
  { name: "Au Sable River – MI", lat: 44.65, lng: -84.22, category: "river", state: "Michigan", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Manistee River", lat: 44.38, lng: -85.72, category: "river", state: "Michigan", species: ["Steelhead","Chinook Salmon","Brown Trout"] },
  { name: "Muskegon River", lat: 43.52, lng: -85.92, category: "river", state: "Michigan", species: ["Steelhead","Chinook Salmon","Walleye"] },
  { name: "Houghton Lake", lat: 44.32, lng: -84.75, category: "lake", state: "Michigan", species: ["Walleye","Largemouth Bass","Bluegill"] },
  { name: "Lake St. Clair", lat: 42.43, lng: -82.78, category: "lake", state: "Michigan", species: ["Smallmouth Bass","Muskellunge","Walleye","Yellow Perch"] },
  { name: "Detroit River", lat: 42.28, lng: -83.12, category: "river", state: "Michigan", species: ["Walleye","Smallmouth Bass","Muskellunge"] },
  { name: "Lake Superior – Keweenaw", lat: 47.22, lng: -88.22, category: "lake", state: "Michigan", species: ["Lake Trout","Brook Trout","Coho Salmon"] },
  { name: "Lake Winnebago", lat: 43.95, lng: -88.42, category: "lake", state: "Wisconsin", species: ["Walleye","White Bass","Sturgeon","Yellow Perch"] },
  { name: "Lake Mendota", lat: 43.10, lng: -89.42, category: "lake", state: "Wisconsin", species: ["Largemouth Bass","Walleye","Panfish"] },
  { name: "Chequamegon Bay", lat: 46.75, lng: -90.82, category: "bay", state: "Wisconsin", species: ["Smallmouth Bass","Walleye","Lake Trout"] },
  { name: "Wolf River – WI", lat: 44.68, lng: -88.85, category: "river", state: "Wisconsin", species: ["Muskellunge","Walleye","Smallmouth Bass"] },
  { name: "St. Croix River", lat: 45.38, lng: -92.65, category: "river", state: "Wisconsin/Minnesota", species: ["Smallmouth Bass","Muskellunge","Walleye"] },
  { name: "Flambeau River", lat: 45.72, lng: -90.22, category: "river", state: "Wisconsin", species: ["Muskellunge","Smallmouth Bass","Walleye"] },
  { name: "Mille Lacs Lake", lat: 46.22, lng: -93.58, category: "lake", state: "Minnesota", species: ["Walleye","Smallmouth Bass","Muskellunge","Yellow Perch"] },
  { name: "Lake of the Woods", lat: 49.00, lng: -94.75, category: "lake", state: "Minnesota", species: ["Walleye","Sauger","Northern Pike","Smallmouth Bass"] },
  { name: "Rainy River", lat: 48.82, lng: -94.58, category: "river", state: "Minnesota", species: ["Walleye","Sturgeon","Sauger","Smallmouth Bass"] },
  { name: "Leech Lake", lat: 47.12, lng: -94.45, category: "lake", state: "Minnesota", species: ["Walleye","Muskellunge","Northern Pike","Yellow Perch"] },
  { name: "Upper Red Lake", lat: 48.08, lng: -94.88, category: "lake", state: "Minnesota", species: ["Walleye","Northern Pike","Crappie"] },
  { name: "Boundary Waters – Basswood", lat: 48.08, lng: -91.55, category: "lake", state: "Minnesota", species: ["Walleye","Smallmouth Bass","Northern Pike","Lake Trout"] },
  { name: "Mississippi River – Pool 4", lat: 44.25, lng: -91.98, category: "river", state: "Minnesota/Wisconsin", species: ["Walleye","Sauger","Smallmouth Bass","Catfish"] },
  { name: "Lake Pepin", lat: 44.48, lng: -92.18, category: "lake", state: "Minnesota/Wisconsin", species: ["Walleye","Sauger","Smallmouth Bass"] },
  { name: "Spirit Lake", lat: 43.42, lng: -95.12, category: "lake", state: "Iowa", species: ["Walleye","Yellow Perch","Muskellunge","Smallmouth Bass"] },
  { name: "West Okoboji Lake", lat: 43.38, lng: -95.17, category: "lake", state: "Iowa", species: ["Walleye","Smallmouth Bass","Muskellunge","Yellow Perch"] },
  { name: "Mississippi River – Pool 9", lat: 43.12, lng: -91.15, category: "river", state: "Iowa/Wisconsin", species: ["Walleye","Sauger","Largemouth Bass","Catfish"] },
  { name: "Rathbun Lake", lat: 40.82, lng: -92.88, category: "reservoir", state: "Iowa", species: ["Channel Catfish","Crappie","Walleye","Largemouth Bass"] },

  // MORE GREAT PLAINS
  { name: "Missouri River – Fort Peck", lat: 47.62, lng: -106.95, category: "river", state: "Montana", species: ["Walleye","Sauger","Northern Pike","Smallmouth Bass"] },
  { name: "Flathead Lake", lat: 47.88, lng: -114.08, category: "lake", state: "Montana", species: ["Lake Trout","Bull Trout","Yellow Perch","Lake Whitefish"] },
  { name: "Bighorn River", lat: 45.72, lng: -107.58, category: "river", state: "Montana", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Missouri River – Craig", lat: 47.00, lng: -112.12, category: "river", state: "Montana", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Rock Creek – MT", lat: 46.68, lng: -113.68, category: "stream", state: "Montana", species: ["Rainbow Trout","Brown Trout","Bull Trout","Cutthroat Trout"] },
  { name: "Bitterroot River", lat: 46.38, lng: -114.08, category: "river", state: "Montana", species: ["Rainbow Trout","Brown Trout","Bull Trout"] },
  { name: "Yellowstone River – Livingston", lat: 45.65, lng: -110.55, category: "river", state: "Montana", species: ["Cutthroat Trout","Brown Trout","Rainbow Trout"] },
  { name: "Madison River", lat: 45.55, lng: -111.58, category: "river", state: "Montana", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Gallatin River", lat: 45.58, lng: -111.18, category: "river", state: "Montana", species: ["Rainbow Trout","Brown Trout","Cutthroat Trout"] },
  { name: "North Platte River – WY", lat: 42.72, lng: -106.35, category: "river", state: "Wyoming", species: ["Rainbow Trout","Brown Trout","Walleye"] },
  { name: "Snake River – WY", lat: 43.58, lng: -110.82, category: "river", state: "Wyoming", species: ["Cutthroat Trout","Brown Trout","Lake Trout"] },
  { name: "Green River – WY", lat: 41.52, lng: -109.48, category: "river", state: "Wyoming", species: ["Brown Trout","Rainbow Trout","Mountain Whitefish"] },
  { name: "Flaming Gorge Reservoir", lat: 41.08, lng: -109.58, category: "reservoir", state: "Wyoming/Utah", species: ["Lake Trout","Kokanee Salmon","Smallmouth Bass","Rainbow Trout"] },
  { name: "Bighorn Lake", lat: 44.98, lng: -108.18, category: "reservoir", state: "Wyoming/Montana", species: ["Walleye","Brown Trout","Largemouth Bass"] },
  { name: "Boysen Reservoir", lat: 43.42, lng: -108.18, category: "reservoir", state: "Wyoming", species: ["Walleye","Sauger","Brown Trout","Rainbow Trout"] },
  { name: "Oahe Reservoir – SD", lat: 44.42, lng: -100.38, category: "reservoir", state: "South Dakota", species: ["Walleye","Smallmouth Bass","Northern Pike","Chinook Salmon"] },
  { name: "Lake Sharpe", lat: 44.05, lng: -99.48, category: "reservoir", state: "South Dakota", species: ["Walleye","Smallmouth Bass","Northern Pike"] },
  { name: "Lewis and Clark Lake", lat: 42.88, lng: -97.48, category: "reservoir", state: "South Dakota/Nebraska", species: ["Walleye","Catfish","White Bass"] },
  { name: "Lake Sakakawea", lat: 47.58, lng: -102.32, category: "reservoir", state: "North Dakota", species: ["Walleye","Smallmouth Bass","Northern Pike","Chinook Salmon"] },
  { name: "Devils Lake", lat: 48.05, lng: -99.05, category: "lake", state: "North Dakota", species: ["Walleye","Yellow Perch","White Bass","Northern Pike"] },
  { name: "Lake Darling", lat: 48.42, lng: -100.42, category: "lake", state: "North Dakota", species: ["Northern Pike","Walleye","Yellow Perch"] },

  // MORE ROCKY MOUNTAIN & WEST
  { name: "Henry's Fork", lat: 44.12, lng: -111.35, category: "river", state: "Idaho", species: ["Rainbow Trout","Brown Trout","Cutthroat Trout"] },
  { name: "South Fork Boise River", lat: 43.58, lng: -115.28, category: "river", state: "Idaho", species: ["Rainbow Trout","Brown Trout","Bull Trout"] },
  { name: "Silver Creek – ID", lat: 43.32, lng: -114.12, category: "stream", state: "Idaho", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Salmon River – ID", lat: 45.18, lng: -114.05, category: "river", state: "Idaho", species: ["Steelhead","Chinook Salmon","Bull Trout"] },
  { name: "Clearwater River – ID", lat: 46.42, lng: -116.78, category: "river", state: "Idaho", species: ["Steelhead","Chinook Salmon","Smallmouth Bass"] },
  { name: "Priest Lake", lat: 48.52, lng: -116.88, category: "lake", state: "Idaho", species: ["Lake Trout","Bull Trout","Cutthroat Trout"] },
  { name: "Lake Pend Oreille", lat: 48.18, lng: -116.52, category: "lake", state: "Idaho", species: ["Rainbow Trout","Bull Trout","Lake Trout","Kokanee Salmon"] },
  { name: "Green River – UT Below Flaming Gorge", lat: 40.92, lng: -109.42, category: "river", state: "Utah", species: ["Brown Trout","Rainbow Trout","Colorado Pikeminnow"] },
  { name: "Provo River", lat: 40.55, lng: -111.48, category: "river", state: "Utah", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Weber River", lat: 41.18, lng: -111.92, category: "river", state: "Utah", species: ["Brown Trout","Rainbow Trout","Mountain Whitefish"] },
  { name: "Strawberry Reservoir", lat: 40.18, lng: -111.12, category: "reservoir", state: "Utah", species: ["Cutthroat Trout","Rainbow Trout","Kokanee Salmon"] },
  { name: "Lake Powell", lat: 37.08, lng: -111.25, category: "reservoir", state: "Utah/Arizona", species: ["Largemouth Bass","Striped Bass","Walleye","Smallmouth Bass"] },
  { name: "Bear Lake", lat: 42.00, lng: -111.32, category: "lake", state: "Utah/Idaho", species: ["Bonneville Cutthroat Trout","Lake Trout","Cisco"] },
  { name: "San Juan River", lat: 36.78, lng: -108.68, category: "river", state: "New Mexico", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Rio Grande – NM", lat: 36.55, lng: -105.58, category: "river", state: "New Mexico", species: ["Rio Grande Cutthroat Trout","Brown Trout","Rainbow Trout"] },
  { name: "Elephant Butte Reservoir", lat: 33.22, lng: -107.18, category: "reservoir", state: "New Mexico", species: ["Largemouth Bass","Striped Bass","Walleye","Catfish"] },
  { name: "Navajo Lake – NM", lat: 36.80, lng: -107.62, category: "reservoir", state: "New Mexico", species: ["Kokanee Salmon","Largemouth Bass","Northern Pike","Brown Trout"] },
  { name: "Colorado River – Lees Ferry", lat: 36.87, lng: -111.60, category: "river", state: "Arizona", species: ["Rainbow Trout"] },
  { name: "Lake Pleasant", lat: 33.85, lng: -112.28, category: "reservoir", state: "Arizona", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Roosevelt Lake", lat: 33.68, lng: -111.18, category: "reservoir", state: "Arizona", species: ["Largemouth Bass","Smallmouth Bass","Crappie","Catfish"] },
  { name: "Apache Lake", lat: 33.55, lng: -111.25, category: "reservoir", state: "Arizona", species: ["Largemouth Bass","Walleye","Yellow Bass"] },

  // MORE PACIFIC NORTHWEST
  { name: "Columbia River – Astoria", lat: 46.18, lng: -123.82, category: "river", state: "Oregon", species: ["Chinook Salmon","Steelhead","Sturgeon"] },
  { name: "Deschutes River", lat: 44.72, lng: -121.25, category: "river", state: "Oregon", species: ["Rainbow Trout","Brown Trout","Steelhead"] },
  { name: "Rogue River", lat: 42.42, lng: -124.42, category: "river", state: "Oregon", species: ["Chinook Salmon","Steelhead","Smallmouth Bass"] },
  { name: "Umpqua River", lat: 43.55, lng: -124.10, category: "river", state: "Oregon", species: ["Chinook Salmon","Steelhead","Smallmouth Bass","Shad"] },
  { name: "Williamson River", lat: 42.68, lng: -121.88, category: "river", state: "Oregon", species: ["Rainbow Trout","Brown Trout","Brook Trout"] },
  { name: "Crane Prairie Reservoir", lat: 43.78, lng: -121.78, category: "reservoir", state: "Oregon", species: ["Rainbow Trout","Brook Trout","Largemouth Bass"] },
  { name: "Diamond Lake", lat: 43.18, lng: -122.15, category: "lake", state: "Oregon", species: ["Rainbow Trout","Tiger Trout"] },
  { name: "Tillamook Bay", lat: 45.52, lng: -123.88, category: "bay", state: "Oregon", species: ["Chinook Salmon","Lingcod","Rockfish","Crab"] },
  { name: "Puget Sound – San Juan Islands", lat: 48.55, lng: -123.05, category: "bay", state: "Washington", species: ["Chinook Salmon","Lingcod","Rockfish","Halibut"] },
  { name: "Skagit River", lat: 48.45, lng: -121.45, category: "river", state: "Washington", species: ["Steelhead","Chinook Salmon","Bull Trout"] },
  { name: "Yakima River", lat: 46.58, lng: -120.52, category: "river", state: "Washington", species: ["Rainbow Trout","Cutthroat Trout","Smallmouth Bass"] },
  { name: "Olympic Peninsula – Hoh River", lat: 47.82, lng: -124.22, category: "river", state: "Washington", species: ["Steelhead","Chinook Salmon","Bull Trout"] },
  { name: "Lake Chelan", lat: 47.88, lng: -120.22, category: "lake", state: "Washington", species: ["Chinook Salmon","Lake Trout","Rainbow Trout"] },
  { name: "Banks Lake", lat: 47.72, lng: -119.15, category: "reservoir", state: "Washington", species: ["Walleye","Smallmouth Bass","Lake Trout","Kokanee Salmon"] },
  { name: "Rufus Woods Lake", lat: 47.95, lng: -119.58, category: "reservoir", state: "Washington", species: ["Rainbow Trout","Walleye","Kokanee Salmon"] },

  // CALIFORNIA
  { name: "Sacramento River – Redding", lat: 40.58, lng: -122.38, category: "river", state: "California", species: ["Chinook Salmon","Steelhead","Rainbow Trout"] },
  { name: "McCloud River", lat: 41.08, lng: -122.12, category: "river", state: "California", species: ["Rainbow Trout","Brown Trout","Brook Trout"] },
  { name: "Hat Creek", lat: 40.82, lng: -121.48, category: "stream", state: "California", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Fall River", lat: 41.02, lng: -121.45, category: "river", state: "California", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Pit River", lat: 41.05, lng: -121.52, category: "river", state: "California", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Lake Shasta", lat: 40.82, lng: -122.32, category: "reservoir", state: "California", species: ["Rainbow Trout","Brown Trout","Largemouth Bass","Spotted Bass"] },
  { name: "Trinity Lake", lat: 40.98, lng: -122.75, category: "reservoir", state: "California", species: ["Smallmouth Bass","Largemouth Bass","Rainbow Trout"] },
  { name: "Eagle Lake – CA", lat: 40.62, lng: -120.72, category: "lake", state: "California", species: ["Eagle Lake Trout"] },
  { name: "Lake Berryessa", lat: 38.58, lng: -122.22, category: "reservoir", state: "California", species: ["Largemouth Bass","Rainbow Trout","Kokanee Salmon"] },
  { name: "Clear Lake – CA", lat: 39.02, lng: -122.78, category: "lake", state: "California", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Sacramento-San Joaquin Delta", lat: 38.05, lng: -121.72, category: "river", state: "California", species: ["Largemouth Bass","Striped Bass","Sturgeon"] },
  { name: "San Francisco Bay", lat: 37.62, lng: -122.22, category: "bay", state: "California", species: ["Striped Bass","Halibut","Sturgeon","Leopard Shark"] },
  { name: "Monterey Bay", lat: 36.80, lng: -121.90, category: "bay", state: "California", species: ["Halibut","Lingcod","Rockfish","Salmon"] },
  { name: "Lake Castaic", lat: 34.55, lng: -118.62, category: "reservoir", state: "California", species: ["Largemouth Bass","Rainbow Trout","Catfish"] },
  { name: "Lake Casitas", lat: 34.38, lng: -119.32, category: "reservoir", state: "California", species: ["Largemouth Bass","Rainbow Trout","Catfish"] },
  { name: "Diamond Valley Lake", lat: 33.68, lng: -117.18, category: "reservoir", state: "California", species: ["Largemouth Bass","Striped Bass","Rainbow Trout"] },
  { name: "San Diego Bay", lat: 32.68, lng: -117.15, category: "bay", state: "California", species: ["Halibut","Spotted Bay Bass","Corvina","Barracuda"] },
  { name: "Salton Sea", lat: 33.25, lng: -115.82, category: "lake", state: "California", species: ["Corvina","Tilapia","Sargo"] },
  { name: "Owens River – Hot Creek", lat: 37.65, lng: -118.82, category: "stream", state: "California", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Crowley Lake", lat: 37.55, lng: -118.72, category: "reservoir", state: "California", species: ["Rainbow Trout","Brown Trout","Sacramento Perch"] },
  { name: "Convict Lake", lat: 37.58, lng: -118.85, category: "lake", state: "California", species: ["Rainbow Trout","Brown Trout"] },

  // MORE COLORADO
  { name: "South Platte River – Deckers", lat: 39.22, lng: -105.22, category: "river", state: "Colorado", species: ["Rainbow Trout","Brown Trout"] },
  { name: "South Platte River – Cheesman", lat: 39.22, lng: -105.28, category: "river", state: "Colorado", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Arkansas River – Salida", lat: 38.53, lng: -106.00, category: "river", state: "Colorado", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Frying Pan River", lat: 39.35, lng: -106.82, category: "river", state: "Colorado", species: ["Rainbow Trout","Brown Trout","Brook Trout"] },
  { name: "Gunnison River – Black Canyon", lat: 38.55, lng: -107.72, category: "river", state: "Colorado", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Blue Mesa Reservoir", lat: 38.45, lng: -107.22, category: "reservoir", state: "Colorado", species: ["Kokanee Salmon","Lake Trout","Rainbow Trout","Brown Trout"] },
  { name: "Spinney Mountain Reservoir", lat: 39.02, lng: -105.72, category: "reservoir", state: "Colorado", species: ["Northern Pike","Rainbow Trout","Cutthroat Trout"] },
  { name: "Eleven Mile Reservoir", lat: 38.92, lng: -105.58, category: "reservoir", state: "Colorado", species: ["Rainbow Trout","Northern Pike","Kokanee Salmon","Carp"] },
  { name: "Horsetooth Reservoir", lat: 40.55, lng: -105.18, category: "reservoir", state: "Colorado", species: ["Walleye","Smallmouth Bass","Rainbow Trout"] },
  { name: "Williams Fork Reservoir", lat: 39.98, lng: -106.18, category: "reservoir", state: "Colorado", species: ["Northern Pike","Rainbow Trout","Brown Trout","Lake Trout"] },

  // MORE KANSAS, NEBRASKA, OKLAHOMA
  { name: "Milford Reservoir", lat: 39.08, lng: -96.88, category: "reservoir", state: "Kansas", species: ["Walleye","White Bass","Crappie","Catfish"] },
  { name: "El Dorado Reservoir", lat: 37.82, lng: -96.82, category: "reservoir", state: "Kansas", species: ["Walleye","Striped Bass","Crappie"] },
  { name: "Lake McConaughy", lat: 41.22, lng: -101.95, category: "reservoir", state: "Nebraska", species: ["Walleye","White Bass","Channel Catfish","Smallmouth Bass"] },
  { name: "Calamus Reservoir", lat: 41.78, lng: -99.52, category: "reservoir", state: "Nebraska", species: ["Walleye","Northern Pike","Largemouth Bass"] },
  { name: "Merritt Reservoir", lat: 42.55, lng: -100.92, category: "reservoir", state: "Nebraska", species: ["Walleye","Muskellunge","Largemouth Bass"] },
  { name: "Broken Bow Reservoir", lat: 34.38, lng: -94.72, category: "reservoir", state: "Oklahoma", species: ["Largemouth Bass","Smallmouth Bass","Catfish"] },
  { name: "Grand Lake O' the Cherokees", lat: 36.62, lng: -94.82, category: "reservoir", state: "Oklahoma", species: ["Largemouth Bass","Crappie","Catfish","Paddlefish"] },
  { name: "Lake Tenkiller", lat: 35.62, lng: -94.95, category: "reservoir", state: "Oklahoma", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Mountain Fork River", lat: 34.22, lng: -94.68, category: "river", state: "Oklahoma", species: ["Rainbow Trout","Brown Trout"] },
  { name: "Lower Illinois River – OK", lat: 35.88, lng: -94.78, category: "river", state: "Oklahoma", species: ["Smallmouth Bass","Largemouth Bass","Channel Catfish"] },

  // MORE ARKANSAS
  { name: "White River – Bull Shoals", lat: 36.38, lng: -92.58, category: "river", state: "Arkansas", species: ["Brown Trout","Rainbow Trout","Cutthroat Trout"] },
  { name: "Norfork Tailwater", lat: 36.25, lng: -92.22, category: "river", state: "Arkansas", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Little Red River", lat: 35.52, lng: -92.22, category: "river", state: "Arkansas", species: ["Brown Trout","Rainbow Trout","Cutthroat Trout"] },
  { name: "Beaver Lake", lat: 36.32, lng: -93.82, category: "reservoir", state: "Arkansas", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Lake Ouachita", lat: 34.55, lng: -93.22, category: "reservoir", state: "Arkansas", species: ["Largemouth Bass","Striped Bass","Crappie","Walleye"] },
  { name: "Norfolk Lake", lat: 36.42, lng: -92.25, category: "reservoir", state: "Arkansas", species: ["Largemouth Bass","Crappie","Walleye"] },

  // MORE KENTUCKY / TENNESSEE
  { name: "Dale Hollow Lake", lat: 36.55, lng: -85.42, category: "reservoir", state: "Kentucky/Tennessee", species: ["Smallmouth Bass","Walleye","Muskellunge","Trout"] },
  { name: "Lake Cumberland", lat: 36.88, lng: -84.95, category: "reservoir", state: "Kentucky", species: ["Striped Bass","Walleye","Largemouth Bass","Crappie"] },
  { name: "Kentucky Lake", lat: 36.62, lng: -88.08, category: "reservoir", state: "Kentucky/Tennessee", species: ["Largemouth Bass","Crappie","Catfish","Sauger"] },
  { name: "Lake Barkley", lat: 36.85, lng: -87.88, category: "reservoir", state: "Kentucky", species: ["Largemouth Bass","Crappie","Sauger","Catfish"] },
  { name: "Green River – KY", lat: 37.25, lng: -86.28, category: "river", state: "Kentucky", species: ["Muskellunge","Smallmouth Bass","Spotted Bass"] },
  { name: "Elkhorn Creek", lat: 38.22, lng: -84.78, category: "stream", state: "Kentucky", species: ["Smallmouth Bass","Rock Bass","Longear Sunfish"] },
  { name: "South Holston Lake", lat: 36.52, lng: -82.08, category: "reservoir", state: "Tennessee", species: ["Smallmouth Bass","Walleye","Trout"] },
  { name: "South Holston River", lat: 36.55, lng: -82.12, category: "river", state: "Tennessee", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Clinch River – TN", lat: 36.22, lng: -84.15, category: "river", state: "Tennessee", species: ["Brown Trout","Rainbow Trout","Muskellunge"] },
  { name: "Watauga Lake", lat: 36.32, lng: -82.12, category: "reservoir", state: "Tennessee", species: ["Smallmouth Bass","Walleye","Brown Trout"] },

  // MORE VIRGINIA / WEST VIRGINIA
  { name: "Smith River – VA", lat: 36.72, lng: -80.05, category: "river", state: "Virginia", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Jackson River", lat: 37.82, lng: -79.95, category: "river", state: "Virginia", species: ["Brown Trout","Rainbow Trout"] },
  { name: "Mossy Creek", lat: 38.35, lng: -79.02, category: "stream", state: "Virginia", species: ["Brown Trout","Rainbow Trout","Brook Trout"] },
  { name: "Lake Anna", lat: 38.05, lng: -77.82, category: "reservoir", state: "Virginia", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Claytor Lake", lat: 37.05, lng: -80.62, category: "reservoir", state: "Virginia", species: ["Striped Bass","Largemouth Bass","Crappie","Walleye"] },
  { name: "New River – VA", lat: 37.22, lng: -80.85, category: "river", state: "Virginia", species: ["Smallmouth Bass","Muskellunge","Rock Bass"] },
  { name: "Shenandoah River – South Fork", lat: 38.58, lng: -78.82, category: "river", state: "Virginia", species: ["Smallmouth Bass","Redbreast Sunfish","Channel Catfish"] },
  { name: "Cheat River", lat: 39.45, lng: -79.68, category: "river", state: "West Virginia", species: ["Smallmouth Bass","Rock Bass","Channel Catfish"] },
  { name: "Williams River", lat: 38.38, lng: -80.32, category: "stream", state: "West Virginia", species: ["Brook Trout","Brown Trout","Rainbow Trout"] },
  { name: "Shavers Fork", lat: 38.72, lng: -79.82, category: "stream", state: "West Virginia", species: ["Brook Trout","Brown Trout","Rainbow Trout"] },

  // ADDITIONAL SCATTERED LOCATIONS
  { name: "Lake Champlain – Burlington", lat: 44.48, lng: -73.22, category: "lake", state: "Vermont", species: ["Lake Trout","Landlocked Salmon","Smallmouth Bass","Northern Pike"] },
  { name: "Susquehanna River – Harrisburg", lat: 40.27, lng: -76.88, category: "river", state: "Pennsylvania", species: ["Smallmouth Bass","Channel Catfish","Muskellunge"] },
  { name: "Allegheny River", lat: 41.82, lng: -79.15, category: "river", state: "Pennsylvania", species: ["Walleye","Muskellunge","Smallmouth Bass"] },
  { name: "Juniata River", lat: 40.55, lng: -77.58, category: "river", state: "Pennsylvania", species: ["Smallmouth Bass","Muskellunge","Channel Catfish"] },
  { name: "Ohio River – Pittsburgh", lat: 40.44, lng: -80.02, category: "river", state: "Pennsylvania", species: ["Walleye","Sauger","Channel Catfish","Smallmouth Bass"] },
  { name: "Conowingo Dam – Susquehanna", lat: 39.66, lng: -76.17, category: "river", state: "Maryland", species: ["Striped Bass","Blue Catfish","Flathead Catfish"] },
  { name: "Potomac River – Great Falls", lat: 38.99, lng: -77.25, category: "river", state: "Virginia/Maryland", species: ["Smallmouth Bass","Largemouth Bass","Blue Catfish"] },
  { name: "Lake Gaston", lat: 36.52, lng: -78.02, category: "reservoir", state: "Virginia/North Carolina", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Kerr Lake (Buggs Island)", lat: 36.62, lng: -78.32, category: "reservoir", state: "Virginia/North Carolina", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Santee Cooper – Lake Marion", lat: 33.48, lng: -80.18, category: "reservoir", state: "South Carolina", species: ["Striped Bass","Largemouth Bass","Catfish","Crappie"] },
  { name: "Winyah Bay", lat: 33.32, lng: -79.22, category: "bay", state: "South Carolina", species: ["Red Drum","Flounder","Spotted Seatrout"] },
  { name: "Lake Seminole", lat: 30.78, lng: -84.88, category: "reservoir", state: "Georgia/Florida", species: ["Largemouth Bass","Crappie","Catfish"] },
  { name: "Flint River – GA", lat: 32.18, lng: -84.22, category: "river", state: "Georgia", species: ["Shoal Bass","Largemouth Bass","Catfish"] },
  { name: "Altamaha River", lat: 31.35, lng: -81.52, category: "river", state: "Georgia", species: ["Largemouth Bass","Redbreast Sunfish","Catfish"] },
  { name: "Lake Lanier", lat: 34.28, lng: -83.95, category: "reservoir", state: "Georgia", species: ["Spotted Bass","Largemouth Bass","Striped Bass"] },
  { name: "Lake Oconee", lat: 33.58, lng: -83.28, category: "reservoir", state: "Georgia", species: ["Largemouth Bass","Striped Bass","Crappie"] },
  { name: "Cumberland Island – GA", lat: 30.85, lng: -81.45, category: "bay", state: "Georgia", species: ["Red Drum","Flounder","Spotted Seatrout","Tarpon"] },
  { name: "Perdido Bay", lat: 30.32, lng: -87.42, category: "bay", state: "Alabama/Florida", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Destin – East Pass", lat: 30.38, lng: -86.52, category: "bay", state: "Florida", species: ["Red Snapper","Cobia","King Mackerel","Mahi-Mahi"] },
  { name: "Panama City Beach", lat: 30.18, lng: -85.82, category: "bay", state: "Florida", species: ["Red Snapper","Grouper","Cobia","King Mackerel"] },
  { name: "Steinhatchee", lat: 29.67, lng: -83.38, category: "bay", state: "Florida", species: ["Red Drum","Speckled Trout","Cobia","Grouper"] },
  { name: "Crystal River – FL", lat: 28.88, lng: -82.62, category: "river", state: "Florida", species: ["Redfish","Snook","Tarpon","Sheepshead"] },
  { name: "Homosassa River", lat: 28.78, lng: -82.62, category: "river", state: "Florida", species: ["Tarpon","Red Drum","Snook","Grouper"] },
  { name: "Apalachicola Bay", lat: 29.68, lng: -85.02, category: "bay", state: "Florida", species: ["Red Drum","Speckled Trout","Flounder"] },
  { name: "Pine Island Sound", lat: 26.58, lng: -82.18, category: "bay", state: "Florida", species: ["Snook","Red Drum","Spotted Seatrout","Tarpon"] },
  { name: "Lake Kissimmee", lat: 27.88, lng: -81.22, category: "lake", state: "Florida", species: ["Largemouth Bass","Crappie","Bluegill"] },

  // ADDITIONAL GREAT LAKES
  { name: "Lake Huron – Saginaw Bay", lat: 43.82, lng: -83.52, category: "lake", state: "Michigan", species: ["Walleye","Yellow Perch","Smallmouth Bass","Channel Catfish"] },
  { name: "Lake Superior – Marquette", lat: 46.55, lng: -87.38, category: "lake", state: "Michigan", species: ["Lake Trout","Brook Trout","Coho Salmon"] },
  { name: "Lake Ontario – Henderson Harbor", lat: 43.85, lng: -76.18, category: "lake", state: "New York", species: ["Smallmouth Bass","Walleye","Chinook Salmon","Brown Trout"] },
  { name: "Lake Ontario – Oswego", lat: 43.47, lng: -76.52, category: "lake", state: "New York", species: ["Chinook Salmon","Steelhead","Brown Trout"] },
  { name: "Lake Erie – Dunkirk", lat: 42.48, lng: -79.35, category: "lake", state: "New York", species: ["Walleye","Steelhead","Smallmouth Bass","Perch"] },
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  try {
    // Get existing location names to avoid duplicates
    const { data: existing } = await supabase.from("fishing_locations").select("name");
    const existingNames = new Set((existing || []).map(l => l.name));

    const newLocations = moreLocations.filter(l => !existingNames.has(l.name));

    let inserted = 0;
    for (let i = 0; i < newLocations.length; i += 100) {
      const batch = newLocations.slice(i, i + 100);
      const { error } = await supabase.from("fishing_locations").insert(batch);
      if (error) throw new Error(`Location batch ${i}: ${error.message}`);
      inserted += batch.length;
    }

    return new Response(
      JSON.stringify({ success: true, new_locations_inserted: inserted, duplicates_skipped: moreLocations.length - newLocations.length }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
