import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const moreFish = [
  // ADDITIONAL BASS VARIETIES
  { name_en: "Choctaw Bass", latin_name: "Micropterus haiaka", category: "freshwater", habitat: "Coastal rivers of Alabama and Florida panhandle", techniques: ["Spinning","Fly fishing"], baits: ["Small crankbaits","Jigs","Nymphs"], description: "Recently described species from Gulf Coast drainages." },
  { name_en: "Bartram's Bass", latin_name: "Micropterus sp. cf. coosae", category: "freshwater", habitat: "Savannah River drainage", techniques: ["Fly fishing","Ultralight spinning"], baits: ["Small poppers","Crickets","Nymphs"], description: "Undescribed redeye bass variant from the Savannah basin." },
  { name_en: "Tallapoosa Bass", latin_name: "Micropterus tallapoosae", category: "freshwater", habitat: "Tallapoosa River system, Alabama", techniques: ["Spinning","Fly fishing"], baits: ["Small crankbaits","Jigs"], description: "Endemic bass of the Tallapoosa drainage." },
  { name_en: "Cahaba Bass", latin_name: "Micropterus cahabae", category: "freshwater", habitat: "Cahaba River, Alabama", techniques: ["Spinning","Fly fishing"], baits: ["Crawfish imitations","Small jigs"], description: "Endemic to the Cahaba River system in central Alabama." },
  { name_en: "Warrior Bass", latin_name: "Micropterus warriorensis", category: "freshwater", habitat: "Black Warrior River system", techniques: ["Spinning","Fly fishing"], baits: ["Small crankbaits","Jigs"], description: "Endemic bass of the Black Warrior River drainage." },
  { name_en: "Chattahoochee Bass", latin_name: "Micropterus chattahoochae", category: "freshwater", habitat: "Chattahoochee River above Falls Line", techniques: ["Spinning","Fly fishing"], baits: ["Crawfish imitations","Nymphs"], description: "Recently described species from the upper Chattahoochee." },
  { name_en: "Alabama Bass", latin_name: "Micropterus henshalli", category: "freshwater", habitat: "Mobile River basin", techniques: ["Spinning","Baitcasting"], baits: ["Soft plastics","Crankbaits","Jigs"], description: "Formerly considered spotted bass. Aggressive and growing rapidly in range." },
  { name_en: "Mean Mouth Bass", latin_name: "Micropterus salmoides × dolomieu", category: "freshwater", habitat: "Stocked reservoirs", techniques: ["Spinning","Baitcasting"], baits: ["Soft plastics","Crankbaits"], description: "Hybrid between largemouth and smallmouth bass." },
  { name_en: "Whiterock Bass", latin_name: "Morone chrysops × saxatilis", category: "freshwater", habitat: "Reservoirs across the South", techniques: ["Trolling","Jigging"], baits: ["Live shad","Sassy Shad"], description: "Another name for sunshine bass hybrid. Aggressive schooling fish." },
  { name_en: "Yellow Bass", latin_name: "Morone mississippiensis", category: "freshwater", habitat: "Mississippi River basin lakes", techniques: ["Jigging","Float fishing"], baits: ["Small jigs","Minnows","Worms"], description: "Smallest temperate bass. Schools heavily and fights hard for its size." },

  // MORE SUNFISH
  { name_en: "Redbreast Sunfish", latin_name: "Lepomis auritus", category: "freshwater", habitat: "Atlantic coastal streams", techniques: ["Fly fishing","Float fishing"], baits: ["Crickets","Worms","Small poppers"], description: "Colorful sunfish of eastern streams. Long opercular flap." },
  { name_en: "Mud Sunfish", latin_name: "Acantharchus pomotis", category: "freshwater", habitat: "Coastal plain swamps, NJ to Georgia", techniques: ["Float fishing"], baits: ["Worms","Small minnows"], description: "Secretive sunfish of dark, tannic swamps." },
  { name_en: "Banded Sunfish", latin_name: "Enneacanthus obesus", category: "freshwater", habitat: "Atlantic coastal plain ponds", techniques: ["Float fishing"], baits: ["Tiny worms","Bread"], description: "Small ornate sunfish of acidic coastal plain waters." },
  { name_en: "Blackbanded Sunfish", latin_name: "Enneacanthus chaetodon", category: "freshwater", habitat: "Coastal plain from NJ to Florida", techniques: ["Float fishing"], baits: ["Tiny worms","Micro jigs"], description: "Beautiful small sunfish with bold black bars." },
  { name_en: "Bluespotted Sunfish", latin_name: "Enneacanthus gloriosus", category: "freshwater", habitat: "Atlantic and Gulf coastal plains", techniques: ["Float fishing"], baits: ["Worms","Bread"], description: "Sparkling blue-spotted sunfish of quiet waters." },
  { name_en: "Pygmy Sunfish (Elassoma)", latin_name: "Elassoma zonatum", category: "freshwater", habitat: "Swamps and ditches of southeastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks with worm bits"], description: "Tiny sunfish relative, barely an inch long. Popular with micro fishers." },
  { name_en: "Everglades Pygmy Sunfish", latin_name: "Elassoma evergladei", category: "freshwater", habitat: "Florida wetlands", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "One of smallest North American fish. Found in Florida's marshes." },

  // DARTERS (popular with micro-fishing)
  { name_en: "Rainbow Darter", latin_name: "Etheostoma caeruleum", category: "freshwater", habitat: "Clear rocky streams, eastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks","Micro nymphs"], description: "Brilliantly colored small fish. Males display stunning rainbow colors." },
  { name_en: "Orangethroat Darter", latin_name: "Etheostoma spectabile", category: "freshwater", habitat: "Ozark and prairie streams", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Colorful darter of central US streams." },
  { name_en: "Fantail Darter", latin_name: "Etheostoma flabellare", category: "freshwater", habitat: "Rocky streams, eastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Common darter with fan-shaped tail." },
  { name_en: "Greenside Darter", latin_name: "Etheostoma blennioides", category: "freshwater", habitat: "Rocky riffles, eastern US", techniques: ["Micro fishing"], baits: ["Tiny nymphs"], description: "One of the larger darters. Green bars on sides." },
  { name_en: "Logperch", latin_name: "Percina caprodes", category: "freshwater", habitat: "Sandy streams and lake margins", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Largest common darter. Uses snout to flip rocks for food." },
  { name_en: "Johnny Darter", latin_name: "Etheostoma nigrum", category: "freshwater", habitat: "Sandy streams across eastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "One of most widespread darters. Rests on bottom on pectoral fins." },
  { name_en: "Iowa Darter", latin_name: "Etheostoma exile", category: "freshwater", habitat: "Vegetated lakes and streams", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Slender darter found in weedy areas across northern US." },
  { name_en: "Snail Darter", latin_name: "Percina tanasi", category: "freshwater", habitat: "Tennessee River tributaries", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Famous for the Tellico Dam controversy. Small endangered darter." },
  { name_en: "Candy Darter", latin_name: "Etheostoma osburni", category: "freshwater", habitat: "New River tributaries, WV and VA", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Stunning candy-striped darter. Threatened by hybridization." },

  // MORE CATFISH
  { name_en: "Yellow Bullhead", latin_name: "Ameiurus natalis", category: "freshwater", habitat: "Ponds, slow streams", techniques: ["Bottom fishing","Float fishing"], baits: ["Worms","Chicken liver"], description: "Yellowish catfish with white chin barbels. Common in warm waters." },
  { name_en: "Brown Bullhead", latin_name: "Ameiurus nebulosus", category: "freshwater", habitat: "Ponds, lakes, slow rivers", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait","Stink bait"], description: "Most widespread bullhead. Mottled brown with dark chin barbels." },
  { name_en: "Black Bullhead", latin_name: "Ameiurus melas", category: "freshwater", habitat: "Muddy ponds, ditches", techniques: ["Bottom fishing"], baits: ["Worms","Chicken liver"], description: "Tolerates low oxygen. Dark-colored with black chin barbels." },
  { name_en: "Spotted Bullhead", latin_name: "Ameiurus serracanthus", category: "freshwater", habitat: "Spring-fed rivers of FL, GA, AL", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Light spots on dark body. Found in clear limestone streams." },
  { name_en: "Snail Bullhead", latin_name: "Ameiurus brunneus", category: "freshwater", habitat: "Southeastern piedmont streams", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Small bullhead of rocky southeastern streams." },
  { name_en: "Tadpole Madtom", latin_name: "Noturus gyrinus", category: "freshwater", habitat: "Vegetated ponds and streams", techniques: ["Micro fishing"], baits: ["Tiny hooks with worm"], description: "Tiny catfish with venomous pectoral spines." },
  { name_en: "Stonecat", latin_name: "Noturus flavus", category: "freshwater", habitat: "Rocky riffles of central US", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish"], description: "Largest madtom. Yellowish with rounded tail. Mildly venomous." },
  { name_en: "Margined Madtom", latin_name: "Noturus insignis", category: "freshwater", habitat: "Rocky streams, eastern US", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Common madtom of Appalachian streams." },

  // MORE PIKE & PICKEREL
  { name_en: "Chain Pickerel", latin_name: "Esox niger", category: "freshwater", habitat: "Ponds, lakes, slow rivers of eastern US", techniques: ["Spinning","Live bait"], baits: ["Spinners","Live minnows","Soft plastics"], description: "Distinctive chain-like markings. Most common pickerel." },
  { name_en: "Redfin Pickerel", latin_name: "Esox americanus americanus", category: "freshwater", habitat: "Coastal plain streams, eastern US", techniques: ["Ultralight spinning"], baits: ["Small spinners","Minnows"], description: "Small pickerel with red fins. Found in sluggish streams." },
  { name_en: "Grass Pickerel", latin_name: "Esox americanus vermiculatus", category: "freshwater", habitat: "Weedy streams and ponds", techniques: ["Ultralight spinning"], baits: ["Small spinners","Minnows"], description: "Smallest pike family member. Hides in vegetation." },
  { name_en: "Tiger Muskie", latin_name: "Esox masquinongy × lucius", category: "freshwater", habitat: "Stocked lakes and reservoirs", techniques: ["Trolling","Casting"], baits: ["Large spinners","Jerkbaits","Swimbaits"], description: "Sterile hybrid pike-muskie. Tiger-striped pattern. Grows fast." },

  // STURGEON
  { name_en: "White Sturgeon", latin_name: "Acipenser transmontanus", category: "anadromous", habitat: "Pacific coast rivers, Columbia and Snake rivers", techniques: ["Bottom fishing"], baits: ["Shrimp","Nightcrawlers","Smelt"], description: "Largest North American freshwater fish. Can exceed 1,000 lbs." },
  { name_en: "Green Sturgeon", latin_name: "Acipenser medirostris", category: "anadromous", habitat: "Pacific coast, Sacramento River", techniques: ["Bottom fishing"], baits: ["Shrimp","Ghost shrimp"], description: "Threatened species. More oceanic than white sturgeon." },
  { name_en: "Atlantic Sturgeon", latin_name: "Acipenser oxyrinchus", category: "anadromous", habitat: "Atlantic coast rivers", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Endangered. Historically important fishery. Now protected." },
  { name_en: "Gulf Sturgeon", latin_name: "Acipenser oxyrinchus desotoi", category: "anadromous", habitat: "Gulf coast rivers from FL to LA", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Threatened subspecies of Atlantic sturgeon." },
  { name_en: "Shortnose Sturgeon", latin_name: "Acipenser brevirostrum", category: "anadromous", habitat: "Atlantic coast rivers", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Endangered small sturgeon of eastern rivers." },
  { name_en: "Lake Sturgeon", latin_name: "Acipenser fulvescens", category: "freshwater", habitat: "Great Lakes, large rivers", techniques: ["Bottom fishing"], baits: ["Nightcrawlers","Cut bait"], description: "Largest Great Lakes fish. Can live over 100 years." },
  { name_en: "Pallid Sturgeon", latin_name: "Scaphirhynchus albus", category: "freshwater", habitat: "Missouri and Mississippi rivers", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Critically endangered. Pale-colored bottom dweller." },
  { name_en: "Shovelnose Sturgeon", latin_name: "Scaphirhynchus platorynchus", category: "freshwater", habitat: "Missouri and Mississippi rivers", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Smallest US sturgeon. Flat shovel-shaped snout." },
  { name_en: "Paddlefish", latin_name: "Polyodon spathula", category: "freshwater", habitat: "Mississippi basin large rivers", techniques: ["Snagging","Bow fishing"], baits: ["Snagging (plankton feeder)"], description: "Prehistoric fish with paddle-shaped snout. Filter feeder." },

  // GAR
  { name_en: "Longnose Gar", latin_name: "Lepisosteus osseus", category: "freshwater", habitat: "Rivers, lakes across eastern US", techniques: ["Bow fishing","Live bait"], baits: ["Live minnows","Rope lures"], description: "Most widespread gar. Long narrow snout with sharp teeth." },
  { name_en: "Shortnose Gar", latin_name: "Lepisosteus platostomus", category: "freshwater", habitat: "Mississippi basin", techniques: ["Bow fishing","Live bait"], baits: ["Live minnows","Cut bait"], description: "Shortest snout of all gars. Found in turbid waters." },
  { name_en: "Spotted Gar", latin_name: "Lepisosteus oculatus", category: "freshwater", habitat: "Clear vegetated lakes, Gulf states", techniques: ["Live bait","Bow fishing"], baits: ["Live minnows","Rope lures"], description: "Spotted body and head. Found in clear weedy waters." },
  { name_en: "Florida Gar", latin_name: "Lepisosteus platyrhincus", category: "freshwater", habitat: "Florida peninsula waterways", techniques: ["Live bait","Bow fishing"], baits: ["Live shiners","Cut bait"], description: "Endemic to Florida. Similar to spotted gar." },
  { name_en: "Alligator Gar", latin_name: "Atractosteus spatula", category: "freshwater", habitat: "Gulf coast rivers, reservoirs", techniques: ["Live bait","Bow fishing"], baits: ["Large live bait","Cut carp"], description: "Largest gar species. Can exceed 300 lbs. Prehistoric appearance." },
  { name_en: "Tropical Gar", latin_name: "Atractosteus tropicus", category: "freshwater", habitat: "Rio Grande drainage (rare in US)", techniques: ["Live bait"], baits: ["Live minnows"], description: "Extremely rare in US waters. Found in southernmost Texas." },

  // BOWFIN
  { name_en: "Bowfin", latin_name: "Amia calva", category: "freshwater", habitat: "Vegetated lakes, swamps, eastern US", techniques: ["Live bait","Spinning"], baits: ["Live bait","Cut bait","Soft plastics"], description: "Living fossil. Only surviving member of its family. Aggressive fighter." },

  // SHAD & HERRING
  { name_en: "American Shad", latin_name: "Alosa sapidissima", category: "anadromous", habitat: "Atlantic coast rivers during spawning", techniques: ["Fly fishing","Spinning"], baits: ["Shad darts","Small jigs","Flies"], description: "Largest American herring. Epic spring spawning runs." },
  { name_en: "Hickory Shad", latin_name: "Alosa mediocris", category: "anadromous", habitat: "Atlantic coast rivers", techniques: ["Fly fishing","Spinning"], baits: ["Small jigs","Flies","Shad darts"], description: "Smaller cousin of American shad. Strong fighter for its size." },
  { name_en: "Alewife", latin_name: "Alosa pseudoharengus", category: "anadromous", habitat: "Atlantic coast, Great Lakes", techniques: ["Dip netting","Spinning"], baits: ["Small jigs","Sabiki rigs"], description: "Important forage fish. Landlocked populations in Great Lakes." },
  { name_en: "Blueback Herring", latin_name: "Alosa aestivalis", category: "anadromous", habitat: "Atlantic coast rivers", techniques: ["Dip netting","Spinning"], baits: ["Sabiki rigs","Small jigs"], description: "Similar to alewife but prefers warmer water." },
  { name_en: "Gizzard Shad", latin_name: "Dorosoma cepedianum", category: "freshwater", habitat: "Lakes and rivers across eastern US", techniques: ["Cast netting"], baits: ["Primarily used as bait"], description: "Important forage fish. Filter feeder with gizzard-like stomach." },
  { name_en: "Threadfin Shad", latin_name: "Dorosoma petenense", category: "freshwater", habitat: "Southern reservoirs", techniques: ["Cast netting"], baits: ["Used as bait fish"], description: "Key forage species in southern reservoirs. Dies in cold water." },
  { name_en: "Skipjack Herring", latin_name: "Alosa chrysochloris", category: "freshwater", habitat: "Mississippi basin large rivers", techniques: ["Spinning"], baits: ["Small jigs","Spoons"], description: "Acrobatic silver fish. Excellent bait for blue catfish." },

  // SMELT
  { name_en: "Rainbow Smelt", latin_name: "Osmerus mordax", category: "anadromous", habitat: "Great Lakes, Northeast coastal waters", techniques: ["Dip netting","Ice fishing"], baits: ["Tiny hooks","Small jigs"], description: "Popular ice fishing target. Spawning runs in spring." },
  { name_en: "Eulachon", latin_name: "Thaleichthys pacificus", category: "anadromous", habitat: "Pacific Northwest rivers", techniques: ["Dip netting"], baits: ["Dip nets during runs"], description: "Also called candlefish. So oily it can be burned like a candle." },

  // WHITEFISH & CISCO
  { name_en: "Lake Whitefish", latin_name: "Coregonus clupeaformis", category: "freshwater", habitat: "Great Lakes, northern lakes", techniques: ["Ice fishing","Jigging","Fly fishing"], baits: ["Wax worms","Small jigs","Nymphs"], description: "Important commercial and sport fish of Great Lakes." },
  { name_en: "Mountain Whitefish", latin_name: "Prosopium williamsoni", category: "freshwater", habitat: "Western mountain streams and lakes", techniques: ["Fly fishing","Spinning"], baits: ["Nymphs","Small spinners","Worms"], description: "Common in western trout streams. Often caught while trout fishing." },
  { name_en: "Round Whitefish", latin_name: "Prosopium cylindraceum", category: "freshwater", habitat: "Northern lakes and rivers", techniques: ["Ice fishing","Bottom fishing"], baits: ["Worms","Wax worms"], description: "Cylindrical whitefish of cold northern waters." },
  { name_en: "Cisco (Lake Herring)", latin_name: "Coregonus artedi", category: "freshwater", habitat: "Great Lakes, northern lakes", techniques: ["Ice fishing","Fly fishing"], baits: ["Small jigs","Tiny flies"], description: "Pelagic whitefish. Important forage and sport fish." },
  { name_en: "Bloater", latin_name: "Coregonus hoyi", category: "freshwater", habitat: "Deep waters of Great Lakes", techniques: ["Deep jigging"], baits: ["Small jigs"], description: "Deep-water cisco of the Great Lakes." },
  { name_en: "Inconnu (Sheefish)", latin_name: "Stenodus leucichthys", category: "freshwater", habitat: "Alaska rivers", techniques: ["Spinning","Fly fishing"], baits: ["Spoons","Streamers","Spinners"], description: "Large predatory whitefish of Alaska. Can exceed 60 lbs." },

  // MOONEYE & GOLDEYE
  { name_en: "Mooneye", latin_name: "Hiodon tergisus", category: "freshwater", habitat: "Clear rivers and lakes, central US", techniques: ["Fly fishing","Ultralight spinning"], baits: ["Small flies","Tiny spinners"], description: "Silver fish with large eyes. Excellent fly rod target." },
  { name_en: "Goldeye", latin_name: "Hiodon alosoides", category: "freshwater", habitat: "Turbid rivers, northern plains", techniques: ["Fly fishing","Spinning"], baits: ["Small jigs","Flies"], description: "Gold-eyed relative of mooneye. Smoked goldeye is a delicacy." },

  // DRUM & SHEEPSHEAD
  { name_en: "Freshwater Drum", latin_name: "Aplodinotus grunniens", category: "freshwater", habitat: "Large rivers, lakes across central US", techniques: ["Bottom fishing","Spinning"], baits: ["Crawfish","Worms","Jigs"], description: "Only freshwater member of drum family. Makes drumming sounds." },

  // SUCKERS
  { name_en: "White Sucker", latin_name: "Catostomus commersonii", category: "freshwater", habitat: "Streams and lakes across northern US", techniques: ["Bottom fishing"], baits: ["Worms","Dough bait"], description: "Most widespread sucker. Important spring spawning runs." },
  { name_en: "Longnose Sucker", latin_name: "Catostomus catostomus", category: "freshwater", habitat: "Cold streams and lakes", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish"], description: "Northern sucker with elongated snout." },
  { name_en: "Largescale Sucker", latin_name: "Catostomus macrocheilus", category: "freshwater", habitat: "Pacific Northwest streams and lakes", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Common sucker of western streams." },
  { name_en: "Spotted Sucker", latin_name: "Minytrema melanops", category: "freshwater", habitat: "Clear streams, eastern US", techniques: ["Bottom fishing"], baits: ["Worms","Dough"], description: "Rows of dark spots on scales. Found in clean streams." },
  { name_en: "Northern Hogsucker", latin_name: "Hypentelium nigricans", category: "freshwater", habitat: "Clear rocky streams", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Distinctive saddle-marked sucker. Indicator of clean water." },
  { name_en: "River Redhorse", latin_name: "Moxostoma carinatum", category: "freshwater", habitat: "Large clean rivers", techniques: ["Bottom fishing"], baits: ["Crawfish","Worms"], description: "Large sucker with red fins. Powerful fighter." },
  { name_en: "Golden Redhorse", latin_name: "Moxostoma erythrurum", category: "freshwater", habitat: "Streams and rivers, eastern US", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish"], description: "Golden-colored sucker common in Midwest streams." },
  { name_en: "Shorthead Redhorse", latin_name: "Moxostoma macrolepidotum", category: "freshwater", habitat: "Clear rivers and streams", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Most widespread redhorse. Important spring spawner." },
  { name_en: "Greater Redhorse", latin_name: "Moxostoma valenciennesi", category: "freshwater", habitat: "Large rivers, Great Lakes tributaries", techniques: ["Bottom fishing"], baits: ["Crawfish","Worms"], description: "Largest redhorse species. Can exceed 10 lbs." },
  { name_en: "Black Redhorse", latin_name: "Moxostoma duquesnei", category: "freshwater", habitat: "Clear streams, Ohio River basin", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Dark-colored redhorse of clean streams." },
  { name_en: "Silver Redhorse", latin_name: "Moxostoma anisurum", category: "freshwater", habitat: "Large rivers and lakes", techniques: ["Bottom fishing"], baits: ["Worms","Crawfish"], description: "Silvery sucker found in clean large waters." },
  { name_en: "Smallmouth Buffalo", latin_name: "Ictiobus bubalus", category: "freshwater", habitat: "Rivers and reservoirs, central US", techniques: ["Bottom fishing","Bow fishing"], baits: ["Dough bait","Corn","Worms"], description: "Can live over 100 years. Recently found to be incredibly long-lived." },
  { name_en: "Bigmouth Buffalo", latin_name: "Ictiobus cyprinellus", category: "freshwater", habitat: "Large rivers, floodplain lakes", techniques: ["Bow fishing","Bottom fishing"], baits: ["Dough bait","Corn"], description: "Largest sucker. Filter feeds like a carp. Can exceed 70 lbs." },
  { name_en: "Black Buffalo", latin_name: "Ictiobus niger", category: "freshwater", habitat: "Large rivers, Mississippi basin", techniques: ["Bottom fishing"], baits: ["Dough bait","Worms"], description: "Dark-colored buffalo of large river systems." },
  { name_en: "Quillback", latin_name: "Carpiodes cyprinus", category: "freshwater", habitat: "Rivers and lakes, eastern US", techniques: ["Bottom fishing"], baits: ["Worms","Dough"], description: "Elongated dorsal fin ray gives it the quillback name." },
  { name_en: "River Carpsucker", latin_name: "Carpiodes carpio", category: "freshwater", habitat: "Large rivers, central US", techniques: ["Bottom fishing"], baits: ["Dough","Worms"], description: "Common large sucker of prairie rivers." },
  { name_en: "Blue Sucker", latin_name: "Cycleptus elongatus", category: "freshwater", habitat: "Large rivers with strong current", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait"], description: "Bluish elongated sucker of swift large rivers. Declining species." },

  // MINNOWS (larger sportfish-relevant species)
  { name_en: "Creek Chub", latin_name: "Semotilus atromaculatus", category: "freshwater", habitat: "Small streams across eastern US", techniques: ["Ultralight spinning","Fly fishing"], baits: ["Worms","Tiny spinners","Nymphs"], description: "Common stream minnow. Males build pebble nests." },
  { name_en: "Fallfish", latin_name: "Semotilus corporalis", category: "freshwater", habitat: "Clear streams, northeastern US", techniques: ["Fly fishing","Ultralight spinning"], baits: ["Small flies","Spinners","Worms"], description: "Largest eastern minnow. Can exceed 18 inches." },
  { name_en: "Hornyhead Chub", latin_name: "Nocomis biguttatus", category: "freshwater", habitat: "Clear streams, Midwest", techniques: ["Fly fishing","Float fishing"], baits: ["Worms","Small nymphs"], description: "Males develop horn-like tubercles during spawning." },
  { name_en: "River Chub", latin_name: "Nocomis micropogon", category: "freshwater", habitat: "Rocky streams, Appalachian region", techniques: ["Fly fishing"], baits: ["Small nymphs","Worms"], description: "Builds large gravel mound nests used by other species." },
  { name_en: "Colorado Pikeminnow", latin_name: "Ptychocheilus lucius", category: "freshwater", habitat: "Colorado River basin", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Largest North American minnow. Historically reached 6 feet. Endangered." },
  { name_en: "Northern Pikeminnow", latin_name: "Ptychocheilus oregonensis", category: "freshwater", habitat: "Columbia River basin", techniques: ["Spinning","Live bait"], baits: ["Worms","Small fish","Jigs"], description: "Predatory minnow. Bounty programs exist to reduce predation on salmon." },
  { name_en: "Sacramento Pikeminnow", latin_name: "Ptychocheilus grandis", category: "freshwater", habitat: "Central California streams", techniques: ["Spinning"], baits: ["Worms","Small lures"], description: "Large predatory minnow of California. Can reach 4 feet." },
  { name_en: "Peamouth", latin_name: "Mylocheilus caurinus", category: "freshwater", habitat: "Pacific Northwest lakes and rivers", techniques: ["Float fishing","Spinning"], baits: ["Worms","Corn"], description: "Distinctive two-toned minnow of the Northwest." },
  { name_en: "Roundtail Chub", latin_name: "Gila robusta", category: "freshwater", habitat: "Colorado River tributaries", techniques: ["Spinning","Fly fishing"], baits: ["Worms","Small lures"], description: "Native minnow of desert Southwest rivers." },
  { name_en: "Bonytail Chub", latin_name: "Gila elegans", category: "freshwater", habitat: "Colorado River", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Critically endangered. Rarest native fish in Colorado River." },
  { name_en: "Humpback Chub", latin_name: "Gila cypha", category: "freshwater", habitat: "Grand Canyon, Colorado River", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Endangered. Distinctive humped back. Found in Grand Canyon." },

  // CARP & INVASIVE SPECIES
  { name_en: "Common Carp", latin_name: "Cyprinus carpio", category: "freshwater", habitat: "Lakes, rivers, ponds nationwide", techniques: ["Carp fishing","Bottom fishing","Fly fishing"], baits: ["Boilies","Corn","Dough bait","Bread"], description: "Introduced from Europe. Now found in all 50 states. Can exceed 50 lbs." },
  { name_en: "Mirror Carp", latin_name: "Cyprinus carpio (mirror)", category: "freshwater", habitat: "Lakes and rivers", techniques: ["Carp fishing","Bottom fishing"], baits: ["Boilies","Corn","Bread"], description: "Variant of common carp with large scattered scales." },
  { name_en: "Leather Carp", latin_name: "Cyprinus carpio (leather)", category: "freshwater", habitat: "Lakes and rivers", techniques: ["Carp fishing"], baits: ["Boilies","Corn"], description: "Scaleless variant of common carp. Rare in the wild." },
  { name_en: "Grass Carp", latin_name: "Ctenopharyngodon idella", category: "freshwater", habitat: "Lakes, rivers, canals", techniques: ["Float fishing","Fly fishing"], baits: ["Bread","Grass","Corn","Mulberries"], description: "Introduced for aquatic weed control. Herbivorous. Can exceed 80 lbs." },
  { name_en: "Silver Carp", latin_name: "Hypophthalmichthys molitrix", category: "freshwater", habitat: "Mississippi basin rivers", techniques: ["Bow fishing"], baits: ["Snagging/bow fishing only"], description: "Invasive Asian carp. Famous for leaping out of water near boats." },
  { name_en: "Bighead Carp", latin_name: "Hypophthalmichthys nobilis", category: "freshwater", habitat: "Mississippi basin", techniques: ["Bow fishing"], baits: ["Snagging/bow fishing"], description: "Large-headed invasive carp. Filter feeder reaching 100+ lbs." },
  { name_en: "Black Carp", latin_name: "Mylopharyngodon piceus", category: "freshwater", habitat: "Mississippi basin (invasive)", techniques: ["Bottom fishing"], baits: ["Mussels","Snails"], description: "Invasive mollusk-eating carp. Threatens native mussel species." },
  { name_en: "Goldfish", latin_name: "Carassius auratus", category: "freshwater", habitat: "Ponds, lakes (invasive)", techniques: ["Float fishing"], baits: ["Bread","Worms","Corn"], description: "Released pet goldfish can grow large and establish populations." },

  // PIKE FAMILY ADDITIONS
  { name_en: "Northern Pike", latin_name: "Esox lucius", category: "freshwater", habitat: "Lakes, rivers across northern US", techniques: ["Spinning","Live bait","Fly fishing"], baits: ["Large spinners","Spoons","Live bait","Streamers"], description: "Aggressive toothy predator. Found across northern US. Can exceed 40 lbs." },
  { name_en: "Muskellunge", latin_name: "Esox masquinongy", category: "freshwater", habitat: "Clear lakes, rivers of upper Midwest and NE", techniques: ["Trolling","Casting"], baits: ["Large jerkbaits","Bucktails","Swimbaits","Live suckers"], description: "Fish of 10,000 casts. Largest pike family member. Can exceed 60 lbs." },

  // WALLEYE & SAUGER
  { name_en: "Walleye", latin_name: "Sander vitreus", category: "freshwater", habitat: "Lakes and rivers across northern US", techniques: ["Jigging","Trolling","Live bait"], baits: ["Jigs","Crankbaits","Live minnows","Nightcrawlers"], description: "Premier freshwater gamefish. Excellent table fare. Reflective eyes." },
  { name_en: "Sauger", latin_name: "Sander canadensis", category: "freshwater", habitat: "Large rivers, reservoirs", techniques: ["Jigging","Trolling"], baits: ["Jigs","Minnows","Crankbaits"], description: "Smaller cousin of walleye. Darker spots on body. Found in turbid rivers." },
  { name_en: "Saugeye", latin_name: "Sander vitreus × canadensis", category: "freshwater", habitat: "Stocked reservoirs", techniques: ["Jigging","Trolling"], baits: ["Jigs","Crankbaits","Minnows"], description: "Fertile hybrid of walleye and sauger. Grows fast and tolerates warm water." },

  // TEMPERATE PERCH
  { name_en: "Yellow Perch", latin_name: "Perca flavescens", category: "freshwater", habitat: "Lakes, ponds, slow rivers", techniques: ["Float fishing","Jigging","Ice fishing"], baits: ["Minnows","Worms","Small jigs","Wax worms"], description: "Premier panfish. Yellow-green with dark bars. Excellent eating." },

  // SALTWATER & COASTAL SPECIES
  { name_en: "Red Drum (Redfish)", latin_name: "Sciaenops ocellatus", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Surf casting","Fly fishing","Spinning"], baits: ["Cut bait","Shrimp","Gold spoons","Soft plastics"], description: "Iconic inshore gamefish. Spot on tail. Catch and release popular." },
  { name_en: "Black Drum", latin_name: "Pogonias cromis", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Bottom fishing","Surf casting"], baits: ["Crab","Shrimp","Clams"], description: "Largest drum species. Can exceed 100 lbs. Feeds on shellfish." },
  { name_en: "Spotted Seatrout", latin_name: "Cynoscion nebulosus", category: "saltwater", habitat: "Gulf coast estuaries and bays", techniques: ["Spinning","Fly fishing"], baits: ["Soft plastics","Live shrimp","Topwater"], description: "Popular Gulf coast gamefish. Black spots on upper body." },
  { name_en: "Weakfish", latin_name: "Cynoscion regalis", category: "saltwater", habitat: "Atlantic coast bays and estuaries", techniques: ["Spinning","Bottom fishing"], baits: ["Soft plastics","Bucktails","Live bait"], description: "Atlantic cousin of spotted seatrout. Delicate mouth hence 'weak' fish." },
  { name_en: "Snook", latin_name: "Centropomus undecimalis", category: "saltwater", habitat: "Florida coasts, mangroves", techniques: ["Spinning","Fly fishing","Live bait"], baits: ["Live pilchards","Soft plastics","Topwater"], description: "Prized Florida gamefish. Black lateral line. Excellent fighter." },
  { name_en: "Tarpon", latin_name: "Megalops atlanticus", category: "saltwater", habitat: "Florida, Gulf coast", techniques: ["Fly fishing","Live bait","Spinning"], baits: ["Live crabs","Mullet","Large flies"], description: "Silver King. Spectacular leaps. Can exceed 200 lbs. Catch and release." },
  { name_en: "Bonefish", latin_name: "Albula vulpes", category: "saltwater", habitat: "Florida Keys, tropical flats", techniques: ["Fly fishing","Spinning"], baits: ["Shrimp flies","Small jigs","Live shrimp"], description: "Ghost of the flats. Incredible speed. Premier fly fishing target." },
  { name_en: "Permit", latin_name: "Trachinotus falcatus", category: "saltwater", habitat: "Florida Keys, tropical flats", techniques: ["Fly fishing","Spinning"], baits: ["Crab flies","Live crabs","Small jigs"], description: "Holy grail of flats fishing. Extremely wary and selective." },
  { name_en: "Cobia", latin_name: "Rachycentron canadum", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Sight casting","Live bait","Jigging"], baits: ["Live eels","Jigs","Soft plastics"], description: "Powerful open-water fish. Often found near rays and buoys." },
  { name_en: "King Mackerel", latin_name: "Scomberomorus cavalla", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Trolling","Live bait"], baits: ["Live bait fish","Spoons","Plugs"], description: "Smoker king. Fast and toothy. Popular tournament fish." },
  { name_en: "Spanish Mackerel", latin_name: "Scomberomorus maculatus", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Trolling","Casting"], baits: ["Small spoons","Jigs","Got-cha plugs"], description: "Smaller than king mackerel. Fast and fun on light tackle." },
  { name_en: "Wahoo", latin_name: "Acanthocybium solandri", category: "saltwater", habitat: "Offshore Atlantic and Gulf", techniques: ["High-speed trolling"], baits: ["Trolling lures","Rigged baits"], description: "One of fastest fish in the ocean. Excellent eating." },
  { name_en: "Yellowfin Tuna", latin_name: "Thunnus albacares", category: "saltwater", habitat: "Offshore waters", techniques: ["Trolling","Chunking","Jigging"], baits: ["Trolling lures","Live bait","Poppers"], description: "Premier offshore gamefish. Powerful fights. Excellent sashimi." },
  { name_en: "Bluefin Tuna", latin_name: "Thunnus thynnus", category: "saltwater", habitat: "Atlantic offshore", techniques: ["Trolling","Chunking"], baits: ["Live bait","Trolling spreads"], description: "Largest tuna. Can exceed 1,000 lbs. Most valuable fish in the world." },
  { name_en: "Blackfin Tuna", latin_name: "Thunnus atlanticus", category: "saltwater", habitat: "Gulf and Atlantic offshore", techniques: ["Trolling","Chunking"], baits: ["Small trolling lures","Live bait"], description: "Smallest Atlantic tuna. Fun on light tackle." },
  { name_en: "Skipjack Tuna", latin_name: "Katsuwonus pelamis", category: "saltwater", habitat: "Offshore waters", techniques: ["Trolling","Jigging"], baits: ["Small lures","Feathers"], description: "Most abundant tuna. Great live bait for larger gamefish." },
  { name_en: "Albacore Tuna", latin_name: "Thunnus alalunga", category: "saltwater", habitat: "Pacific and Atlantic offshore", techniques: ["Trolling"], baits: ["Cedar plugs","Feather jigs"], description: "White meat tuna. Long pectoral fins. Popular in Pacific." },
  { name_en: "Blue Marlin", latin_name: "Makaira nigricans", category: "saltwater", habitat: "Deep offshore waters", techniques: ["Trolling"], baits: ["Large trolling lures","Rigged baits"], description: "Ultimate billfish. Can exceed 1,000 lbs. Catch and release." },
  { name_en: "White Marlin", latin_name: "Kajikia albida", category: "saltwater", habitat: "Atlantic offshore", techniques: ["Trolling"], baits: ["Ballyhoo","Small trolling lures"], description: "Smaller Atlantic marlin. Popular tournament target." },
  { name_en: "Sailfish", latin_name: "Istiophorus platypterus", category: "saltwater", habitat: "Atlantic and Gulf offshore", techniques: ["Trolling","Kite fishing","Live bait"], baits: ["Live bait","Trolling lures"], description: "Fastest fish in the ocean. Spectacular sail and leaps." },
  { name_en: "Swordfish", latin_name: "Xiphias gladius", category: "saltwater", habitat: "Deep offshore waters", techniques: ["Deep dropping","Night fishing"], baits: ["Squid","Large bait fish"], description: "Deep-water billfish. Night fishing with lights is popular technique." },
  { name_en: "Dolphinfish (Mahi-Mahi)", latin_name: "Coryphaena hippurus", category: "saltwater", habitat: "Offshore weedlines, flotsam", techniques: ["Trolling","Casting","Live bait"], baits: ["Trolling lures","Live bait","Ballyhoo"], description: "Brilliant colors. Fast growing. One of best-eating fish." },
  { name_en: "Pompano", latin_name: "Trachinotus carolinus", category: "saltwater", habitat: "Gulf and Atlantic surf zone", techniques: ["Surf fishing","Float fishing"], baits: ["Sand fleas","Shrimp","Jigs"], description: "Premier table fare. Found in the surf. Compact powerful fighter." },
  { name_en: "Greater Amberjack", latin_name: "Seriola dumerili", category: "saltwater", habitat: "Offshore reefs and wrecks", techniques: ["Jigging","Live bait"], baits: ["Live bait","Butterfly jigs","Poppers"], description: "Reef donkey. Incredibly powerful fighter. Can exceed 100 lbs." },
  { name_en: "Yellowtail Amberjack", latin_name: "Seriola lalandi", category: "saltwater", habitat: "Pacific coast, kelp beds", techniques: ["Live bait","Jigging","Trolling"], baits: ["Live sardines","Iron jigs","Swimbaits"], description: "Premier Pacific sportfish. Powerful runs around kelp." },
  { name_en: "Tripletail", latin_name: "Lobotes surinamensis", category: "saltwater", habitat: "Gulf coast, floating debris", techniques: ["Sight casting","Fly fishing"], baits: ["Live shrimp","Soft plastics"], description: "Floats on its side near buoys and debris. Excellent eating." },
  { name_en: "Red Snapper", latin_name: "Lutjanus campechanus", category: "saltwater", habitat: "Gulf of Mexico reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Cut bait","Squid","Jigs"], description: "King of Gulf reef fish. Highly regulated. Excellent table fare." },
  { name_en: "Vermilion Snapper", latin_name: "Rhomboplites aurorubens", category: "saltwater", habitat: "Gulf and Atlantic reefs", techniques: ["Bottom fishing"], baits: ["Cut bait","Squid","Small jigs"], description: "Beeliners. Smaller but very tasty snapper species." },
  { name_en: "Yellowtail Snapper", latin_name: "Ocyurus chrysurus", category: "saltwater", habitat: "Florida Keys, tropical reefs", techniques: ["Chumming","Bottom fishing"], baits: ["Cut bait","Shrimp","Small jigs"], description: "Beautiful yellow-tailed reef fish. Excellent eating." },
  { name_en: "Mangrove Snapper", latin_name: "Lutjanus griseus", category: "saltwater", habitat: "Mangroves, docks, reefs", techniques: ["Bottom fishing","Live bait"], baits: ["Live shrimp","Cut bait","Small jigs"], description: "Wary snapper found near structure. Tasty and challenging." },
  { name_en: "Mutton Snapper", latin_name: "Lutjanus analis", category: "saltwater", habitat: "Florida reefs and wrecks", techniques: ["Bottom fishing","Live bait"], baits: ["Live bait","Cut bait"], description: "Large snapper with distinctive spot. Excellent eating." },
  { name_en: "Lane Snapper", latin_name: "Lutjanus synagris", category: "saltwater", habitat: "Gulf and Atlantic reefs", techniques: ["Bottom fishing"], baits: ["Cut bait","Shrimp"], description: "Pink snapper with yellow stripes. Common on nearshore reefs." },
  { name_en: "Cubera Snapper", latin_name: "Lutjanus cyanopterus", category: "saltwater", habitat: "Florida and Caribbean reefs", techniques: ["Heavy bottom fishing"], baits: ["Live lobster","Large live bait"], description: "Largest Atlantic snapper. Can exceed 100 lbs." },
  { name_en: "Grouper (Red)", latin_name: "Epinephelus morio", category: "saltwater", habitat: "Gulf of Mexico reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Live bait","Cut bait","Jigs"], description: "Popular Gulf reef fish. Regulated with seasons and size limits." },
  { name_en: "Grouper (Gag)", latin_name: "Mycteroperca microlepis", category: "saltwater", habitat: "Gulf and Atlantic reefs", techniques: ["Bottom fishing","Trolling"], baits: ["Live bait","Jigs","Diving plugs"], description: "Gray grouper. Found near structure. Excellent table fare." },
  { name_en: "Grouper (Black)", latin_name: "Mycteroperca bonaci", category: "saltwater", habitat: "Atlantic and Gulf reefs", techniques: ["Bottom fishing"], baits: ["Live bait","Cut bait"], description: "Large dark grouper. Powerful fighter near reef structure." },
  { name_en: "Grouper (Goliath)", latin_name: "Epinephelus itajara", category: "saltwater", habitat: "Florida reefs, wrecks, bridges", techniques: ["Catch and release only"], baits: ["Heavy tackle required"], description: "Largest Atlantic grouper. Protected. Can exceed 800 lbs." },
  { name_en: "Grouper (Scamp)", latin_name: "Mycteroperca phenax", category: "saltwater", habitat: "Deep reefs, Gulf and Atlantic", techniques: ["Bottom fishing"], baits: ["Live bait","Squid"], description: "Brown spotted grouper. Considered finest eating of all groupers." },
  { name_en: "Sheepshead", latin_name: "Archosargus probatocephalus", category: "saltwater", habitat: "Pilings, jetties, bridges", techniques: ["Bottom fishing"], baits: ["Fiddler crabs","Shrimp","Barnacles"], description: "Human-like teeth for crushing shellfish. Excellent eating. Bait stealers." },
  { name_en: "Tautog (Blackfish)", latin_name: "Tautoga onitis", category: "saltwater", habitat: "Northeast Atlantic rocky areas", techniques: ["Bottom fishing"], baits: ["Green crabs","Asian crabs","Clams"], description: "Northeast reef favorite. Powerful fighter near structure." },
  { name_en: "Black Sea Bass", latin_name: "Centropristis striata", category: "saltwater", habitat: "Atlantic coast reefs and wrecks", techniques: ["Bottom fishing","Jigging"], baits: ["Squid","Clams","Jigs"], description: "Popular Atlantic bottom fish. All born female, change to male." },
  { name_en: "Summer Flounder (Fluke)", latin_name: "Paralichthys dentatus", category: "saltwater", habitat: "Atlantic coast, sandy bottoms", techniques: ["Drifting","Bottom fishing"], baits: ["Bucktails","Strip bait","Live minnows"], description: "Left-eyed flounder. Popular Atlantic flatfish. Ambush predator." },
  { name_en: "Winter Flounder", latin_name: "Pseudopleuronectes americanus", category: "saltwater", habitat: "Northeast Atlantic bays", techniques: ["Bottom fishing"], baits: ["Clam","Worms","Mussel"], description: "Right-eyed flounder. Excellent eating. Spring fishery in Northeast." },
  { name_en: "Southern Flounder", latin_name: "Paralichthys lethostigma", category: "saltwater", habitat: "Gulf and South Atlantic coast", techniques: ["Gigging","Bottom fishing"], baits: ["Live bait","Soft plastics"], description: "Largest Gulf flounder. Fall run fishing is popular." },
  { name_en: "Halibut (Pacific)", latin_name: "Hippoglossus stenolepis", category: "saltwater", habitat: "Pacific coast, Alaska", techniques: ["Bottom fishing","Drift fishing"], baits: ["Herring","Squid","Jigs"], description: "Largest flatfish. Can exceed 400 lbs. Premier Alaska target." },
  { name_en: "Halibut (California)", latin_name: "Paralichthys californicus", category: "saltwater", habitat: "Southern California coast", techniques: ["Drift fishing","Live bait"], baits: ["Live anchovies","Squid","Swimbaits"], description: "Not a true halibut. Popular SoCal target on sandy flats." },
  { name_en: "Lingcod", latin_name: "Ophiodon elongatus", category: "saltwater", habitat: "Pacific coast rocky reefs", techniques: ["Jigging","Live bait"], baits: ["Large swimbaits","Live bait","Jigs"], description: "Toothy predator. Green flesh is normal and delicious." },
  { name_en: "Cabezon", latin_name: "Scorpaenichthys marmoratus", category: "saltwater", habitat: "Pacific coast rocky areas", techniques: ["Bottom fishing"], baits: ["Shrimp","Squid","Cut bait"], description: "Large sculpin of Pacific tide pools and reefs. Excellent eating." },
  { name_en: "Kelp Bass (Calico)", latin_name: "Paralabrax clathratus", category: "saltwater", habitat: "Southern California kelp beds", techniques: ["Live bait","Spinning"], baits: ["Live anchovies","Swimbaits","Soft plastics"], description: "SoCal kelp bed favorite. Aggressive striker." },
  { name_en: "Sand Bass (Barred)", latin_name: "Paralabrax nebulifer", category: "saltwater", habitat: "Southern California sandy areas", techniques: ["Live bait","Jigging"], baits: ["Live bait","Squid","Soft plastics"], description: "Sandy bottom dweller of SoCal. Spawns in huge aggregations." },
  { name_en: "Spotted Bay Bass", latin_name: "Paralabrax maculatofasciatus", category: "saltwater", habitat: "Southern California bays", techniques: ["Light tackle","Fly fishing"], baits: ["Swimbaits","Soft plastics","Flies"], description: "Small but challenging bass of SoCal bays and estuaries." },
  { name_en: "White Seabass", latin_name: "Atractoscion nobilis", category: "saltwater", habitat: "California coast kelp beds", techniques: ["Live bait","Trolling"], baits: ["Live squid","Swimbaits","Trolling jigs"], description: "Large croaker of California. Prized sportfish. Can reach 80 lbs." },
  { name_en: "Corvina (Orangemouth)", latin_name: "Cynoscion xanthulus", category: "saltwater", habitat: "Salton Sea, Gulf of California", techniques: ["Spinning","Live bait"], baits: ["Sinking lures","Live bait","Cut bait"], description: "Corvina of the Salton Sea. Can exceed 30 lbs." },
  { name_en: "California Yellowtail", latin_name: "Seriola dorsalis", category: "saltwater", habitat: "Southern California coast", techniques: ["Live bait","Trolling","Jigging"], baits: ["Live sardines","Iron jigs","Swimbaits"], description: "Pacific yellowtail. Explosive runs. Top SoCal sportfish." },
  { name_en: "Pacific Barracuda", latin_name: "Sphyraena argentea", category: "saltwater", habitat: "Southern California coast", techniques: ["Trolling","Casting"], baits: ["Chrome jigs","Spoons","Live bait"], description: "Toothy predator of SoCal waters. Fun on light tackle." },
  { name_en: "Great Barracuda", latin_name: "Sphyraena barracuda", category: "saltwater", habitat: "Florida and tropical Atlantic", techniques: ["Trolling","Casting"], baits: ["Tube lures","Live bait","Topwater"], description: "Large predator of tropical waters. Lightning-fast strikes." },
  { name_en: "Bluefish", latin_name: "Pomatomus saltatrix", category: "saltwater", habitat: "Atlantic coast", techniques: ["Surf casting","Trolling","Spinning"], baits: ["Cut bait","Poppers","Metal lures"], description: "Choppers. Aggressive schooling predator. Incredible blitzes." },
  { name_en: "Striped Bass (Saltwater)", latin_name: "Morone saxatilis", category: "saltwater", habitat: "Atlantic coast, surf and bays", techniques: ["Surf casting","Live bait","Trolling"], baits: ["Live eels","Bunker","Plugs","Bucktails"], description: "Striper. Most popular Northeast saltwater gamefish." },
  { name_en: "Tautog", latin_name: "Tautoga onitis", category: "saltwater", habitat: "Northeast Atlantic structure", techniques: ["Bottom fishing"], baits: ["Green crabs","Crabs","Clams"], description: "Blackfish. Structure-oriented wrasse. Excellent table fare." },
  { name_en: "Scup (Porgy)", latin_name: "Stenotomus chrysops", category: "saltwater", habitat: "Northeast Atlantic coast", techniques: ["Bottom fishing"], baits: ["Clam","Squid","Worms"], description: "Popular Northeast bottom fish. Schooling. Good eating." },
  { name_en: "Cunner", latin_name: "Tautogolabrus adspersus", category: "saltwater", habitat: "Northeast Atlantic coast", techniques: ["Bottom fishing"], baits: ["Clam","Worms","Small pieces of bait"], description: "Small wrasse. Aggressive bait stealers. Fun for kids." },
  { name_en: "White Perch", latin_name: "Morone americana", category: "saltwater", habitat: "Atlantic coast estuaries, tidal rivers", techniques: ["Spinning","Float fishing","Bottom fishing"], baits: ["Worms","Minnows","Small jigs"], description: "Not a true perch. Temperate bass of brackish waters." },
  { name_en: "Northern Kingfish", latin_name: "Menticirrhus saxatilis", category: "saltwater", habitat: "Atlantic coast surf zone", techniques: ["Surf fishing"], baits: ["Bloodworms","Clam","Shrimp"], description: "Whiting of the Northeast. Sandy bottom dweller." },
  { name_en: "Southern Kingfish", latin_name: "Menticirrhus americanus", category: "saltwater", habitat: "Gulf and South Atlantic surf", techniques: ["Surf fishing"], baits: ["Shrimp","Bloodworms","Cut bait"], description: "Gulf coast whiting. Common in the surf." },
  { name_en: "Spot", latin_name: "Leiostomus xanthurus", category: "saltwater", habitat: "Atlantic and Gulf coast bays", techniques: ["Bottom fishing"], baits: ["Bloodworms","Shrimp","Squid"], description: "Named for spot behind gill. Popular bait and panfish." },
  { name_en: "Atlantic Croaker", latin_name: "Micropogonias undulatus", category: "saltwater", habitat: "Atlantic and Gulf coast", techniques: ["Bottom fishing"], baits: ["Shrimp","Bloodworms","Squid"], description: "Makes croaking sound. Popular inshore bottom fish." },
  { name_en: "Speckled Hind", latin_name: "Epinephelus drummondhayi", category: "saltwater", habitat: "Deep Atlantic reefs", techniques: ["Deep dropping"], baits: ["Cut bait","Squid"], description: "Beautiful deep-water grouper. Highly regulated." },
  { name_en: "Hogfish", latin_name: "Lachnolaimus maximus", category: "saltwater", habitat: "Florida reefs", techniques: ["Spearfishing","Bottom fishing"], baits: ["Shrimp","Small crabs"], description: "Wrasse with pig-like snout. One of tastiest reef fish." },
  { name_en: "Triggerfish (Gray)", latin_name: "Balistes capriscus", category: "saltwater", habitat: "Gulf and Atlantic reefs", techniques: ["Bottom fishing"], baits: ["Squid","Shrimp","Cut bait"], description: "Tough-skinned reef fish. Aggressive biters with strong teeth." },
  { name_en: "Spadefish (Atlantic)", latin_name: "Chaetodipterus faber", category: "saltwater", habitat: "Gulf and Atlantic wrecks, buoys", techniques: ["Bottom fishing","Chumming"], baits: ["Clam","Jellyfish"], description: "Disc-shaped fish found near structure. Excellent eating." },
  { name_en: "Vermillion Rockfish", latin_name: "Sebastes miniatus", category: "saltwater", habitat: "Pacific coast reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Cut bait","Squid","Shrimp"], description: "Bright red rockfish of the Pacific. Slow growing and long-lived." },
  { name_en: "Copper Rockfish", latin_name: "Sebastes caurinus", category: "saltwater", habitat: "Pacific coast rocky areas", techniques: ["Bottom fishing"], baits: ["Cut bait","Squid"], description: "Copper-brown rockfish. Popular shore fishing target." },
  { name_en: "Yelloweye Rockfish", latin_name: "Sebastes ruberrimus", category: "saltwater", habitat: "Deep Pacific reefs", techniques: ["Deep dropping"], baits: ["Cut bait","Squid"], description: "Bright red deep-water rockfish. Can live 120+ years." },
  { name_en: "Bocaccio Rockfish", latin_name: "Sebastes paucispinis", category: "saltwater", habitat: "Pacific coast deep reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Cut bait","Shrimp","Squid"], description: "Large rockfish with big mouth. Once highly overfished." },
  { name_en: "Canary Rockfish", latin_name: "Sebastes pinniger", category: "saltwater", habitat: "Pacific coast reefs", techniques: ["Bottom fishing"], baits: ["Squid","Cut bait"], description: "Bright orange rockfish. Rebuilding from overfishing." },
  { name_en: "Black Rockfish", latin_name: "Sebastes melanops", category: "saltwater", habitat: "Pacific coast, nearshore reefs", techniques: ["Jigging","Spinning"], baits: ["Swimbaits","Jigs","Cut bait"], description: "Dark rockfish popular for shore anglers on the Pacific." },
  { name_en: "Blue Rockfish", latin_name: "Sebastes mystinus", category: "saltwater", habitat: "Pacific coast kelp and reefs", techniques: ["Bottom fishing","Jigging"], baits: ["Squid","Small jigs"], description: "Bluish schooling rockfish of the Pacific." },
  { name_en: "Quillback Rockfish", latin_name: "Sebastes maliger", category: "saltwater", habitat: "Pacific NW rocky reefs", techniques: ["Bottom fishing"], baits: ["Cut bait","Shrimp"], description: "Orange-brown rockfish with tall dorsal spines." },
  { name_en: "China Rockfish", latin_name: "Sebastes nebulosus", category: "saltwater", habitat: "Pacific coast rocky crevices", techniques: ["Bottom fishing"], baits: ["Shrimp","Cut bait"], description: "Black and yellow rockfish. Hides in rocky crevices." },
  { name_en: "Greenling (Kelp)", latin_name: "Hexagrammos decagrammus", category: "saltwater", habitat: "Pacific coast kelp beds", techniques: ["Bottom fishing","Jigging"], baits: ["Shrimp","Worms","Cut bait"], description: "Colorful Pacific fish. Males blue, females brown-spotted." },
  { name_en: "Pacific Cod", latin_name: "Gadus macrocephalus", category: "saltwater", habitat: "Alaska, Pacific NW deep waters", techniques: ["Bottom fishing","Jigging"], baits: ["Herring","Squid","Jigs"], description: "Important commercial and sport fish. Excellent white meat." },
  { name_en: "Atlantic Cod", latin_name: "Gadus morhua", category: "saltwater", habitat: "Northeast Atlantic", techniques: ["Bottom fishing","Jigging"], baits: ["Clam","Jigs","Cut bait"], description: "Historic fishery. Now heavily regulated. Excellent eating." },
  { name_en: "Haddock", latin_name: "Melanogrammus aeglefinus", category: "saltwater", habitat: "Northeast Atlantic", techniques: ["Bottom fishing"], baits: ["Clam","Worms","Jigs"], description: "Black lateral line and thumb print. Popular food fish." },
  { name_en: "Pollock", latin_name: "Pollachius virens", category: "saltwater", habitat: "Northeast Atlantic", techniques: ["Jigging","Bottom fishing"], baits: ["Jigs","Cut bait","Clam"], description: "Aggressive cod relative. Green back. Fun on jigs." },
  { name_en: "Red Hake", latin_name: "Urophycis chuss", category: "saltwater", habitat: "Northeast Atlantic bottom", techniques: ["Bottom fishing"], baits: ["Clam","Squid","Cut bait"], description: "Bottom dwelling cod relative. Excellent eating." },
  { name_en: "White Hake", latin_name: "Urophycis tenuis", category: "saltwater", habitat: "Deep Northeast Atlantic", techniques: ["Bottom fishing"], baits: ["Clam","Squid"], description: "Deep water hake. Flaky white meat." },
  { name_en: "Tilefish (Golden)", latin_name: "Lopholatilus chamaeleonticeps", category: "saltwater", habitat: "Deep Atlantic canyons", techniques: ["Deep dropping"], baits: ["Squid","Cut bait","Clam"], description: "Deep canyon dweller. Excellent lobster-like taste." },
  { name_en: "Tilefish (Blueline)", latin_name: "Caulolatilus microps", category: "saltwater", habitat: "Deep Atlantic and Gulf reefs", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "Smaller tilefish. Found on deep ledges." },
  { name_en: "Vermillion Snapper (Beeliners)", latin_name: "Rhomboplites aurorubens", category: "saltwater", habitat: "Deep reefs, Atlantic and Gulf", techniques: ["Bottom fishing"], baits: ["Squid","Cut bait","Small jigs"], description: "Small tasty snapper caught in deep water." },
  { name_en: "Almaco Jack", latin_name: "Seriola rivoliana", category: "saltwater", habitat: "Offshore wrecks and reefs", techniques: ["Jigging","Live bait"], baits: ["Live bait","Jigs"], description: "Dark amberjack relative. Powerful deep fighter." },
  { name_en: "Rainbow Runner", latin_name: "Elagatis bipinnulata", category: "saltwater", habitat: "Offshore tropical waters", techniques: ["Trolling","Live bait"], baits: ["Small lures","Live bait"], description: "Colorful fast swimmer. Often caught trolling offshore." },
  { name_en: "African Pompano", latin_name: "Alectis ciliaris", category: "saltwater", habitat: "Offshore wrecks and reefs", techniques: ["Jigging","Bottom fishing"], baits: ["Jigs","Live bait"], description: "Impressive diamond-shaped fish. Juveniles have long filaments." },

  // FRESHWATER DRUM RELATIVES & MISC
  { name_en: "Burbot", latin_name: "Lota lota", category: "freshwater", habitat: "Deep cold lakes, northern US", techniques: ["Ice fishing","Bottom fishing"], baits: ["Cut bait","Minnows","Jigs"], description: "Only freshwater cod. Ugly but excellent eating. Active in winter." },
  { name_en: "American Eel", latin_name: "Anguilla rostrata", category: "freshwater", habitat: "Atlantic coast rivers and streams", techniques: ["Bottom fishing"], baits: ["Worms","Cut bait","Chicken liver"], description: "Catadromous – spawns in Sargasso Sea. Found in freshwater for decades." },
  { name_en: "Longnose Gar", latin_name: "Lepisosteus osseus", category: "freshwater", habitat: "Eastern US rivers and lakes", techniques: ["Live bait","Bow fishing"], baits: ["Live minnows","Rope lures"], description: "Prehistoric fish with long bony snout." },

  // CHARS & TROUT additions
  { name_en: "Paiute Cutthroat Trout", latin_name: "Oncorhynchus clarkii seleniris", category: "freshwater", habitat: "Silver King Creek, California", techniques: ["Fly fishing"], baits: ["Small dry flies"], description: "Rarest trout subspecies. No body spots. Protected." },
  { name_en: "Greenback Cutthroat Trout", latin_name: "Oncorhynchus clarkii stomias", category: "freshwater", habitat: "Colorado mountain streams", techniques: ["Fly fishing"], baits: ["Small dry flies","Nymphs"], description: "Colorado state fish. Recovered from near-extinction." },
  { name_en: "Coastal Cutthroat Trout", latin_name: "Oncorhynchus clarkii clarkii", category: "freshwater", habitat: "Pacific Northwest coastal streams", techniques: ["Fly fishing","Spinning"], baits: ["Streamers","Small spinners"], description: "Sea-run cutthroat of the Pacific NW coast." },
  { name_en: "Snake River Cutthroat Trout", latin_name: "Oncorhynchus clarkii behnkei", category: "freshwater", habitat: "Snake River tributaries, Wyoming/Idaho", techniques: ["Fly fishing"], baits: ["Dry flies","Nymphs"], description: "Fine-spotted cutthroat of the Snake River drainage." },
  { name_en: "Redband Trout", latin_name: "Oncorhynchus mykiss gairdneri", category: "freshwater", habitat: "Interior Columbia basin streams", techniques: ["Fly fishing","Spinning"], baits: ["Nymphs","Small spinners"], description: "Interior form of rainbow trout. Red band along lateral line." },
  { name_en: "Eagle Lake Trout", latin_name: "Oncorhynchus mykiss aquilarum", category: "freshwater", habitat: "Eagle Lake, California", techniques: ["Trolling","Fly fishing"], baits: ["Spoons","Streamers"], description: "Unique rainbow trout adapted to alkaline Eagle Lake." },
  { name_en: "Kern River Rainbow Trout", latin_name: "Oncorhynchus mykiss gilberti", category: "freshwater", habitat: "Kern River, California", techniques: ["Fly fishing"], baits: ["Dry flies","Nymphs"], description: "Native rainbow of the Kern River basin. Golden coloring." },
  { name_en: "McCloud River Redband Trout", latin_name: "Oncorhynchus mykiss stonei", category: "freshwater", habitat: "McCloud River, California", techniques: ["Fly fishing"], baits: ["Dry flies","Nymphs"], description: "Original brood stock for hatchery rainbow trout worldwide." },

  // MISC FRESHWATER
  { name_en: "Sauger (duplicate check)", latin_name: "Sander canadensis", category: "freshwater", habitat: "Rivers, reservoirs", techniques: ["Jigging","Trolling"], baits: ["Minnows","Jigs"], description: "Walleye's smaller cousin. Mottled pattern." },
  { name_en: "Warmouth", latin_name: "Lepomis gulosus", category: "freshwater", habitat: "Swamps, ponds, sluggish streams", techniques: ["Float fishing"], baits: ["Worms","Crickets"], description: "Dark sunfish of swampy habitats." },
  { name_en: "Spotted Sunfish (Stumpknocker)", latin_name: "Lepomis punctatus", category: "freshwater", habitat: "SE streams with wood", techniques: ["Float fishing"], baits: ["Crickets","Worms"], description: "Found near submerged wood in flowing water." },
  { name_en: "Rio Grande Cichlid", latin_name: "Herichthys cyanoguttatus", category: "freshwater", habitat: "Texas rivers and streams", techniques: ["Ultralight spinning","Fly fishing"], baits: ["Small jigs","Crickets","Flies"], description: "Only native US cichlid. Found in central Texas." },
  { name_en: "Peacock Bass (Butterfly)", latin_name: "Cichla ocellaris", category: "freshwater", habitat: "South Florida canals", techniques: ["Spinning","Fly fishing"], baits: ["Topwater","Jerkbaits","Streamers"], description: "Introduced tropical gamefish. Explosive strikes. Miami canals." },
  { name_en: "Mayan Cichlid", latin_name: "Mayaheros urophthalmus", category: "freshwater", habitat: "South Florida freshwater", techniques: ["Spinning","Float fishing"], baits: ["Worms","Small jigs"], description: "Invasive cichlid in Florida. Colorful with ocellated tail spot." },
  { name_en: "Oscar", latin_name: "Astronotus ocellatus", category: "freshwater", habitat: "South Florida canals", techniques: ["Float fishing","Spinning"], baits: ["Worms","Crickets","Small jigs"], description: "Invasive aquarium fish established in Florida." },
  { name_en: "Blue Tilapia", latin_name: "Oreochromis aureus", category: "freshwater", habitat: "Florida, Texas warm waters", techniques: ["Float fishing"], baits: ["Bread","Worms","Corn"], description: "Invasive but now established gamefish in warm states." },
  { name_en: "Clown Knifefish", latin_name: "Chitala ornata", category: "freshwater", habitat: "South Florida canals", techniques: ["Live bait","Spinning"], baits: ["Live shiners","Cut bait"], description: "Large invasive Asian fish established in Florida. Can reach 30+ lbs." },
  { name_en: "Snakehead (Northern)", latin_name: "Channa argus", category: "freshwater", habitat: "Potomac River basin, mid-Atlantic", techniques: ["Spinning","Fly fishing","Frogging"], baits: ["Frogs","Soft plastics","Buzzbaits","Streamers"], description: "Invasive air-breathing predator. Excellent fighter and table fare." },
  { name_en: "Snakehead (Bullseye)", latin_name: "Channa marulius", category: "freshwater", habitat: "South Florida canals", techniques: ["Live bait","Spinning"], baits: ["Live fish","Soft plastics"], description: "Large invasive snakehead established in Broward County, FL." },
  { name_en: "Asian Swamp Eel", latin_name: "Monopterus albus", category: "freshwater", habitat: "South Florida, Georgia wetlands", techniques: ["Specialized gear"], baits: ["Worms"], description: "Invasive eel-like fish. Air breather. Spreads through wetlands." },
  { name_en: "Flathead Catfish", latin_name: "Pylodictis olivaris", category: "freshwater", habitat: "Large rivers, deep pools", techniques: ["Bottom fishing","Live bait"], baits: ["Live fish","Large crawfish"], description: "Large predatory catfish. Prefers live prey. Mottled coloring." },
  { name_en: "Wiper (Hybrid Striped Bass)", latin_name: "Morone saxatilis × chrysops", category: "freshwater", habitat: "Stocked reservoirs", techniques: ["Trolling","Casting","Live bait"], baits: ["Live shad","Sassy Shad","Spoons"], description: "Hybrid striper. Aggressive schooling fish. Stocked widely." },
  { name_en: "Freshwater Jellyfish", latin_name: "Craspedacusta sowerbii", category: "freshwater", habitat: "Quiet lakes and reservoirs", techniques: ["Observation only"], baits: ["Not a sportfish"], description: "Tiny freshwater jellyfish found in warm lakes. Not dangerous." },

  // CHARS
  { name_en: "Sunapee Trout (Sunapee Char)", latin_name: "Salvelinus alpinus oquassa", category: "freshwater", habitat: "Deep cold New England lakes", techniques: ["Trolling","Fly fishing"], baits: ["Smelt","Streamers","Spoons"], description: "Rare landlocked char of New England. Brilliantly colored." },
  { name_en: "Blueback Trout", latin_name: "Salvelinus alpinus oquassa", category: "freshwater", habitat: "Maine's Rangeley Lakes", techniques: ["Fly fishing","Trolling"], baits: ["Small flies","Tiny spoons"], description: "Small landlocked Arctic char of Maine." },

  // MISC SALTWATER
  { name_en: "Crevalle Jack", latin_name: "Caranx hippos", category: "saltwater", habitat: "Atlantic and Gulf coasts", techniques: ["Spinning","Fly fishing"], baits: ["Poppers","Live bait","Jigs"], description: "Powerful inshore jack. Aggressive feeder. Not great eating." },
  { name_en: "Bar Jack", latin_name: "Carangoides ruber", category: "saltwater", habitat: "Florida Keys, Caribbean", techniques: ["Spinning","Jigging"], baits: ["Small jigs","Live bait"], description: "Reef jack with blue-black bar. Good eating when small." },
  { name_en: "Horse-eye Jack", latin_name: "Caranx latus", category: "saltwater", habitat: "Tropical Atlantic", techniques: ["Jigging","Live bait"], baits: ["Jigs","Live bait"], description: "Large-eyed tropical jack. Strong fighter." },
  { name_en: "Blue Runner", latin_name: "Caranx crysos", category: "saltwater", habitat: "Atlantic and Gulf coasts", techniques: ["Spinning","Jigging"], baits: ["Small jigs","Sabiki rigs"], description: "Common small jack. Excellent live bait for larger fish." },
  { name_en: "Lookdown", latin_name: "Selene vomer", category: "saltwater", habitat: "Atlantic coast, near pilings", techniques: ["Light tackle"], baits: ["Small jigs","Shrimp"], description: "Bizarre flat silver fish. Found near structure." },
  { name_en: "Remora", latin_name: "Echeneis naucrates", category: "saltwater", habitat: "Tropical waters, attached to hosts", techniques: ["Accidental catch"], baits: ["Cut bait"], description: "Sucker fish. Attaches to sharks, rays, boats." },
  { name_en: "Pinfish", latin_name: "Lagodon rhomboides", category: "saltwater", habitat: "Gulf and Atlantic seagrass", techniques: ["Float fishing"], baits: ["Shrimp","Bread"], description: "Common bait fish. Found in seagrass beds." },
  { name_en: "Pigfish", latin_name: "Orthopristis chrysoptera", category: "saltwater", habitat: "Gulf and Atlantic coast", techniques: ["Bottom fishing"], baits: ["Shrimp","Cut bait"], description: "Grunt family. Named for pig-like sounds." },
  { name_en: "Sand Perch", latin_name: "Diplectrum formosum", category: "saltwater", habitat: "Atlantic and Gulf sandy bottoms", techniques: ["Bottom fishing"], baits: ["Cut bait","Shrimp"], description: "Small colorful bottom fish. Often caught while bottom fishing." },
  { name_en: "Yellowmouth Grouper", latin_name: "Mycteroperca interstitialis", category: "saltwater", habitat: "Deep reefs, Florida and Caribbean", techniques: ["Bottom fishing"], baits: ["Live bait","Cut bait"], description: "Medium grouper with yellow mouth lining." },
  { name_en: "Nassau Grouper", latin_name: "Epinephelus striatus", category: "saltwater", habitat: "Caribbean reefs (protected)", techniques: ["Catch and release only"], baits: ["Protected species"], description: "Critically endangered grouper. Fully protected in US waters." },
  { name_en: "Jewfish (Atlantic Goliath Grouper)", latin_name: "Epinephelus itajara", category: "saltwater", habitat: "Wrecks, bridges, reefs", techniques: ["Heavy tackle"], baits: ["Large live bait"], description: "Enormous grouper. Can exceed 800 lbs. Catch and release." },
  { name_en: "Warsaw Grouper", latin_name: "Hyporthodus nigritus", category: "saltwater", habitat: "Deep Gulf ledges", techniques: ["Deep dropping"], baits: ["Large cut bait","Squid"], description: "Massive deep-water grouper. Can exceed 300 lbs." },
  { name_en: "Snowy Grouper", latin_name: "Hyporthodus niveatus", category: "saltwater", habitat: "Deep Atlantic and Gulf reefs", techniques: ["Deep dropping"], baits: ["Squid","Cut bait"], description: "Deep-water grouper with white spots. Very deep habitat." },
  { name_en: "Yellowfin Grouper", latin_name: "Mycteroperca venenosa", category: "saltwater", habitat: "Caribbean and Florida reefs", techniques: ["Bottom fishing"], baits: ["Live bait","Cut bait"], description: "Colorful grouper with yellow fin margins." },
  { name_en: "Rock Hind", latin_name: "Epinephelus adscensionis", category: "saltwater", habitat: "Atlantic and Gulf reefs", techniques: ["Bottom fishing"], baits: ["Cut bait","Shrimp"], description: "Small orange-spotted grouper. Common on nearshore reefs." },
  { name_en: "Coney", latin_name: "Cephalopholis fulva", category: "saltwater", habitat: "Tropical reefs", techniques: ["Light tackle bottom fishing"], baits: ["Small cut bait"], description: "Small colorful tropical grouper. Variable color phases." },
  { name_en: "Graysby", latin_name: "Cephalopholis cruentata", category: "saltwater", habitat: "Tropical Atlantic reefs", techniques: ["Light tackle"], baits: ["Small cut bait","Shrimp"], description: "Small spotted grouper of tropical reefs." },

  // SHARKS (catch and release sportfishing)
  { name_en: "Blacktip Shark", latin_name: "Carcharhinus limbatus", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Surf fishing","Spinning"], baits: ["Cut bait","Live bait"], description: "Common inshore shark. Spectacular leaps. Catch and release." },
  { name_en: "Bull Shark", latin_name: "Carcharhinus leucas", category: "saltwater", habitat: "Coastal and freshwater", techniques: ["Heavy tackle"], baits: ["Large cut bait","Live bait"], description: "One of few sharks entering freshwater. Powerful and dangerous." },
  { name_en: "Hammerhead Shark (Great)", latin_name: "Sphyrna mokarran", category: "saltwater", habitat: "Tropical and warm-temperate coasts", techniques: ["Heavy tackle"], baits: ["Stingray","Large bait fish"], description: "Largest hammerhead. Can exceed 1,000 lbs. Protected in many areas." },
  { name_en: "Mako Shark (Shortfin)", latin_name: "Isurus oxyrinchus", category: "saltwater", habitat: "Offshore Atlantic and Pacific", techniques: ["Trolling","Live bait"], baits: ["Live bluefish","Mackerel"], description: "Fastest shark. Incredible leaps. Excellent eating when legal." },
  { name_en: "Thresher Shark", latin_name: "Alopias vulpinus", category: "saltwater", habitat: "Pacific and Atlantic offshore", techniques: ["Trolling","Slow trolling"], baits: ["Live mackerel","Trolling lures"], description: "Long tail used to stun prey. Acrobatic fighter." },
  { name_en: "Blue Shark", latin_name: "Prionace glauca", category: "saltwater", habitat: "Offshore deep water", techniques: ["Chumming","Drift fishing"], baits: ["Cut bait","Chum"], description: "Beautiful blue shark. Most abundant pelagic shark." },
  { name_en: "Lemon Shark", latin_name: "Negaprion brevirostris", category: "saltwater", habitat: "Florida, Gulf coast shallows", techniques: ["Heavy tackle"], baits: ["Cut bait","Live bait"], description: "Yellowish shark of shallow tropical waters." },
  { name_en: "Nurse Shark", latin_name: "Ginglymostoma cirratum", category: "saltwater", habitat: "Tropical Atlantic, Florida", techniques: ["Accidental catch"], baits: ["Cut bait"], description: "Docile bottom-dwelling shark. Commonly seen by divers." },
  { name_en: "Bonnethead Shark", latin_name: "Sphyrna tiburo", category: "saltwater", habitat: "Gulf and Atlantic inshore", techniques: ["Light tackle"], baits: ["Shrimp","Cut bait"], description: "Smallest hammerhead. Common in bays and estuaries." },
  { name_en: "Spinner Shark", latin_name: "Carcharhinus brevipinna", category: "saltwater", habitat: "Gulf and Atlantic coasts", techniques: ["Surf fishing"], baits: ["Cut bait","Live bait"], description: "Leaps and spins when hooked. Similar to blacktip." },

  // RAYS (sportfishing)
  { name_en: "Cownose Ray", latin_name: "Rhinoptera bonasus", category: "saltwater", habitat: "Atlantic and Gulf coasts", techniques: ["Bow fishing","Sight casting"], baits: ["Cut bait","Crab"], description: "Migratory ray. Large schools in Chesapeake Bay." },
  { name_en: "Southern Stingray", latin_name: "Hypanus americanus", category: "saltwater", habitat: "Atlantic and Gulf sandy flats", techniques: ["Accidental catch"], baits: ["Cut bait"], description: "Large stingray of sandy bottoms. Venomous spine." },
  { name_en: "Eagle Ray (Spotted)", latin_name: "Aetobatus narinari", category: "saltwater", habitat: "Tropical Atlantic", techniques: ["Sight casting"], baits: ["Clam","Crab"], description: "Beautiful spotted ray. Leaps clear of water." },

  // MORE FRESHWATER MISC
  { name_en: "Cutlips Minnow", latin_name: "Exoglossum maxillingua", category: "freshwater", habitat: "Appalachian streams", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Unusual three-lobed lower lip. Northeastern streams." },
  { name_en: "Stoneroller", latin_name: "Campostoma anomalum", category: "freshwater", habitat: "Rocky streams across eastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Algae scraper with hard ridge on lower jaw." },
  { name_en: "Redside Dace", latin_name: "Clinostomus elongatus", category: "freshwater", habitat: "Clean headwater streams", techniques: ["Micro fishing"], baits: ["Tiny flies","Micro hooks"], description: "Beautiful small minnow with red stripe. Indicator of clean water." },
  { name_en: "Southern Redbelly Dace", latin_name: "Chrosomus erythrogaster", category: "freshwater", habitat: "Springs and spring-fed streams", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Brilliant red and gold breeding males. Spring-fed habitat." },
  { name_en: "Blacknose Dace", latin_name: "Rhinichthys atratulus", category: "freshwater", habitat: "Rocky streams, eastern US", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Common small minnow of cool streams." },
  { name_en: "Longnose Dace", latin_name: "Rhinichthys cataractae", category: "freshwater", habitat: "Fast rocky streams across US", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Widespread dace found in riffle habitat coast to coast." },
  { name_en: "Speckled Dace", latin_name: "Rhinichthys osculus", category: "freshwater", habitat: "Western streams and springs", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Most widespread native western minnow." },
  { name_en: "Desert Pupfish", latin_name: "Cyprinodon macularius", category: "freshwater", habitat: "Desert springs and streams of Southwest", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Endangered pupfish surviving in extreme desert conditions." },
  { name_en: "Devils Hole Pupfish", latin_name: "Cyprinodon diabolis", category: "freshwater", habitat: "Devils Hole, Death Valley", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Rarest fish in the world. Found only in one small pool in Nevada." },
  { name_en: "Pahrump Poolfish", latin_name: "Empetrichthys latos", category: "freshwater", habitat: "Pahrump Valley, Nevada", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Extremely rare. Found only in a few refugium populations." },
  { name_en: "White River Springfish", latin_name: "Crenichthys baileyi", category: "freshwater", habitat: "White River Valley, Nevada", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Endangered springfish of Nevada's thermal springs." },
  { name_en: "Cui-ui", latin_name: "Chasmistes cujus", category: "freshwater", habitat: "Pyramid Lake, Nevada", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Endangered sucker sacred to the Paiute people. Pyramid Lake only." },
  { name_en: "June Sucker", latin_name: "Chasmistes liorus", category: "freshwater", habitat: "Utah Lake, Utah", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Critically endangered. Found only in Utah Lake." },
  { name_en: "Razorback Sucker", latin_name: "Xyrauchen texanus", category: "freshwater", habitat: "Colorado River basin", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Distinctive razor-like keel. Endangered Colorado River native." },
  { name_en: "Woundfin", latin_name: "Plagopterus argentissimus", category: "freshwater", habitat: "Virgin River, Utah/Arizona", techniques: ["Protected – no fishing"], baits: ["Protected species"], description: "Tiny endangered minnow with sharp dorsal spine." },
  { name_en: "Tui Chub", latin_name: "Siphateles bicolor", category: "freshwater", habitat: "Great Basin lakes and streams", techniques: ["Float fishing"], baits: ["Worms","Bread"], description: "Common Great Basin minnow. Multiple subspecies." },
  { name_en: "Lahontan Redside", latin_name: "Richardsonius egregius", category: "freshwater", habitat: "Great Basin streams", techniques: ["Micro fishing"], baits: ["Tiny hooks"], description: "Colorful Great Basin minnow with red sides." },
  { name_en: "Sacramento Blackfish", latin_name: "Orthodon microlepidotus", category: "freshwater", habitat: "Central California sloughs", techniques: ["Float fishing"], baits: ["Worms","Bread"], description: "Large native minnow of the Sacramento Valley." },
  { name_en: "Hardhead", latin_name: "Mylopharodon conocephalus", category: "freshwater", habitat: "Central California rivers", techniques: ["Bottom fishing"], baits: ["Worms"], description: "Large California native minnow. Hard pharyngeal teeth." },
  { name_en: "Hitch", latin_name: "Lavinia exilicauda", category: "freshwater", habitat: "Central California lakes and streams", techniques: ["Float fishing"], baits: ["Worms","Bread"], description: "California native minnow. Surface feeder." },
  { name_en: "Splittail", latin_name: "Pogonichthys macrolepidotus", category: "freshwater", habitat: "Sacramento-San Joaquin Delta", techniques: ["Float fishing"], baits: ["Worms"], description: "Large native minnow with deeply forked tail." },
  { name_en: "Utah Chub", latin_name: "Gila atraria", category: "freshwater", habitat: "Utah and adjacent states lakes", techniques: ["Float fishing"], baits: ["Worms","Bread","Corn"], description: "Abundant in Bear Lake and other Utah waters." },
  { name_en: "Least Brook Lamprey", latin_name: "Lampetra aepyptera", category: "freshwater", habitat: "Small streams, eastern US", techniques: ["Not a sportfish"], baits: ["N/A"], description: "Non-parasitic lamprey. Indicator of stream health." },
  { name_en: "Sea Lamprey", latin_name: "Petromyzon marinus", category: "anadromous", habitat: "Great Lakes (invasive), Atlantic coast", techniques: ["Not typically targeted"], baits: ["N/A"], description: "Parasitic jawless fish. Major invasive pest in Great Lakes." },
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  try {
    // Get existing fish names to avoid duplicates
    const { data: existing } = await supabase.from("fish_species").select("name_en");
    const existingNames = new Set((existing || []).map(f => f.name_en));

    const newFish = moreFish.filter(f => !existingNames.has(f.name_en));

    let inserted = 0;
    for (let i = 0; i < newFish.length; i += 100) {
      const batch = newFish.slice(i, i + 100);
      const { error } = await supabase.from("fish_species").insert(batch);
      if (error) throw new Error(`Fish batch ${i}: ${error.message}`);
      inserted += batch.length;
    }

    return new Response(
      JSON.stringify({ success: true, new_fish_inserted: inserted, duplicates_skipped: moreFish.length - newFish.length }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
